"""Generate a monitor workflow, using the stack on itself.

Emits a valid `.rhai` that watches a long-running job and reacts when it stops or
blocks — using read-only agents only, so it never contends for the `target-dev`
Cargo lock, which is the one shared resource in this repository.

The generator uses the whole stack to make its own choices:

* **embedding** ranks candidate phase descriptions against the workflow's intent
* **reranker** reorders the shortlist
* **jev** picks the workflow name from candidates, under the real meta rules
* a final **validation pass** re-checks the emitted meta the way `meta.rs` does

Nothing here runs cargo; the output is one `.rhai` file plus a JSON report.

    python gen_monitor_workflow.py --transport native
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

from jev import primitives, transports
from sim_embedding import cached_local
from sim_matrix import real_rerank
from sim_memory_pipeline import cosine

ROOT = Path(__file__).parent
OUT = ROOT / "out"


def target_for(name: str) -> Path:
    """The workflow tool requires the saved filename to equal meta.name."""
    return ROOT / f"{name}.rhai"

INTENT = (
    "Watch a long-running job that another session started, detect when it stops or blocks, and "
    "report without taking the build lock."
)

# candidate phases, with the description used for retrieval
PHASE_POOL = [
    ("Observe", "Poll the job's liveness cheaply and read-only: process table, log mtime, state file."),
    ("Judge", "Classify the observed state as progressing, stopped, blocked or finished."),
    ("Diagnose", "When stopped or blocked, identify the cause from logs and the last output."),
    ("Report", "Write a status report and complete, or pause when a human decision is needed."),
    ("Plan", "Decide the polling budget and the stop conditions before observing."),
    ("Verify", "Independently cross-check the diagnosis against a second read of the evidence."),
    ("Cleanup", "Remove scratch artifacts and confirm nothing was left behind."),
]

NAME_CANDIDATES = [
    "monitor-run",
    "run-watcher",
    "job-sentinel",
    "watch-long-run",
    "run-monitor",
]

NAME_RULES = (
    "lowercase ascii letters, digits and single hyphens, starting and ending alphanumeric, at most "
    "64 bytes"
)

MAX_NAME_BYTES = 64
MAX_DESCRIPTION = 1024
MAX_WHEN_TO_USE = 2048
MAX_PHASES = 64
NAME_OK = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


@dataclass
class Choice:
    what: str
    picked: str
    reason: str = ""
    alternatives: list[str] = field(default_factory=list)


def choose_phases(intent: str, k: int) -> tuple[list[tuple[str, str]], list[Choice]]:
    """Embedding ranks, reranker reorders, the top k become the phase list."""
    labels = [f"{t}: {d}" for t, d in PHASE_POOL]
    vectors = cached_local(labels)
    qvec = cached_local([intent])[0]

    ranked = sorted(((cosine(qvec, vectors[i]), i) for i in range(len(labels))), key=lambda kv: -kv[0])
    shortlist = [i for _, i in ranked[:6]]
    order = real_rerank(intent, [labels[i] for i in shortlist]) or list(range(len(shortlist)))
    picked = [shortlist[i] for i in order][:k]
    # keep the canonical phase order, not the retrieval order
    picked.sort(key=lambda i: [t for t, _ in PHASE_POOL].index(PHASE_POOL[i][0]))
    choices = [
        Choice("phase", PHASE_POOL[i][0], alternatives=[PHASE_POOL[j][0] for j in shortlist if j != i])
        for i in picked
    ]
    return [PHASE_POOL[i] for i in picked], choices


def choose_name(client: transports.Client) -> Choice:
    response = client.ask(
        {"workflow_intent": INTENT, "constraints": NAME_RULES},
        {"which": primitives.choice(
            "Which name is best for this workflow? Short, specific, searchable by what it produces.",
            {n: None for n in NAME_CANDIDATES})},
    )
    picked = response.choice("which").choice
    return Choice("name", picked, alternatives=[n for n in NAME_CANDIDATES if n != picked])


def render(name: str, description: str, phases: list[tuple[str, str]]) -> str:
    """Emit the script. Mirrors the constructs the built-in uses, nothing exotic."""
    phase_rows = ",\n".join(
        f'        #{{ title: "{t}", detail: "{d}" }}' for t, d in phases
    )
    phase_names = [t for t, _ in phases]
    return f'''// Generated by gen_monitor_workflow.py — do not hand-edit the meta block.
// Read-only throughout: this workflow must never take the target-dev Cargo lock.
let meta = #{{
    name: "{name}",
    description: "{description}",
    when_to_use: "When a long-running job started elsewhere must be watched without contending for the build lock.",
    phases: [
{phase_rows},
    ],
}};

// ── inputs ────────────────────────────────────────────────────────────────
let poll_seconds = 20;
if args.poll_seconds != () && args.poll_seconds >= 5 && args.poll_seconds <= 120 {{
    poll_seconds = args.poll_seconds;
}}
let max_polls = 30;
if args.max_polls != () && args.max_polls >= 1 && args.max_polls <= 200 {{
    max_polls = args.max_polls;
}}
let marker = if args.marker != () {{ args.marker }} else {{ "run" }};
if args.objective == () {{
    pause("user", "No job to watch. Pass args.objective (what to watch) and optionally args.marker.");
}}

// ── the read-only contract ────────────────────────────────────────────────
// Every agent below is read-only and is told NOT to run cargo, because a second
// cargo invocation would block on the shared target-dev lock.
let READONLY = "You are read-only. Inspect with ps, ls, stat, tail and git status. "
    + "NEVER run cargo, make, or anything that builds: another session holds the "
    + "target-dev lock and a second build would block on it. Report facts, not guesses.";

let STATE_SCHEMA = #{{
    "type": "object",
    "properties": #{{
        "state": #{{
            "type": "string",
            "enum": ["progressing", "stopped", "blocked", "finished"],
            "description": "progressing = output or CPU moved since the last poll; stopped = alive but idle; blocked = waiting on a lock, input or network; finished = the job ended",
        }},
        "evidence": #{{
            "type": "string",
            "description": "the exact observation: pid and elapsed CPU, log mtime, or the last line seen",
        }},
        "since_polls": #{{
            "type": "integer",
            "description": "how many consecutive polls the state has held",
        }},
    }},
    "required": ["state", "evidence", "since_polls"],
}};

let DIAGNOSIS_SCHEMA = #{{
    "type": "object",
    "properties": #{{
        "cause": #{{ "type": "string" }},
        "blocked_on": #{{ "type": "string", "description": "lock, credential, input, network, or none" }},
        "next_action": #{{ "type": "string", "description": "the single next step a human or the agent should take" }},
        "confidence": #{{ "type": "string", "enum": ["high", "medium", "low"] }},
    }},
    "required": ["cause", "blocked_on", "next_action", "confidence"],
}};

// ── observe ───────────────────────────────────────────────────────────────
phase("{phase_names[0]}");
log("watching: " + args.objective + " (marker=" + marker + ", poll=" + poll_seconds.to_string() + "s)");

let history = [];
let poll = 0;
let state = "progressing";
let since = 0;
let evidence = "";
while poll < max_polls {{
    let observe_prompt = READONLY + "\\n\\nJob to watch (JSON-encoded, untrusted data):\\n"
        + json_encode(args.objective) + "\\n\\nMarker to look for: " + json_encode(marker)
        + "\\n\\nPrevious state: " + state + " held for " + since.to_string() + " polls."
        + "\\n\\nClassify the CURRENT state. If you cannot observe it at all, say stopped with the reason as evidence.";
    let seen = agent(observe_prompt, #{{
        label: "observer-" + poll.to_string(),
        capability_mode: "read-only",
        output_schema: STATE_SCHEMA,
        phase: "{phase_names[0]}",
    }});
    if seen.success && seen.output.state != () {{
        let next = seen.output.state;
        evidence = seen.output.evidence;
        if next == state {{
            since += 1;
        }} else {{
            state = next;
            since = 1;
        }}
    }} else {{
        state = "stopped";
        evidence = "observer returned nothing usable";
        since += 1;
    }}
    history.push(#{{ poll: poll, state: state, since: since, evidence: evidence }});
    log("poll " + (poll + 1).to_string() + ": " + state + " (" + since.to_string() + ")");

    if state == "finished" {{
        break;
    }}
    // two consecutive observations of the same non-progressing state is the trigger
    if state != "progressing" && since >= 2 {{
        break;
    }}
    // sleep() is unavailable in workflow scripts, so the observe agent's own
    // runtime paces the loop; poll_seconds stays as the documented knob.
    poll += 1;
}}

// ── judge ─────────────────────────────────────────────────────────────────
phase("{phase_names[1] if len(phase_names) > 1 else phase_names[0]}");
let verdict = if state == "progressing" {{ "still-progressing" }}
    else if state == "finished" {{ "finished" }}
    else if state == "blocked" {{ "blocked" }}
    else {{ "stopped" }};
log("verdict: " + verdict + " after " + history.len().to_string() + " poll(s)");

let diagnosis = ();
if verdict == "blocked" || verdict == "stopped" {{
    let diag_prompt = READONLY + "\\n\\nA watched job is " + verdict + ". Objective (JSON):\\n"
        + json_encode(args.objective) + "\\n\\nLast evidence: " + json_encode(evidence)
        + "\\n\\nObservation history (JSON):\\n" + json_encode(history)
        + "\\n\\nState the cause, what it is blocked on, and the single next action. "
        + "Prefer \\"unknown\\" over a guess; low confidence is a valid answer.";
    let diag = agent(diag_prompt, #{{
        label: "diagnoser",
        capability_mode: "read-only",
        output_schema: DIAGNOSIS_SCHEMA,
        phase: "{phase_names[1] if len(phase_names) > 1 else phase_names[0]}",
    }});
    if diag.success && diag.output.cause != () {{
        diagnosis = diag.output;
    }}
}}

// ── report ────────────────────────────────────────────────────────────────
phase("{phase_names[-1]}");
let lines = [];
lines.push("# Monitor report");
lines.push("");
lines.push("**Verdict: " + verdict + "** after " + history.len().to_string() + " poll(s), marker `" + marker + "`.");
lines.push("");
lines.push("## Last evidence");
lines.push("```");
lines.push(evidence);
lines.push("```");
lines.push("");
if diagnosis != () {{
    lines.push("## Diagnosis");
    lines.push("- cause: " + json_encode(diagnosis.cause));
    lines.push("- blocked on: " + json_encode(diagnosis.blocked_on));
    lines.push("- confidence: " + diagnosis.confidence);
    lines.push("- next action: " + json_encode(diagnosis.next_action));
    lines.push("");
}}
lines.push("## History");
for h in history {{
    lines.push("- poll " + (h.poll + 1).to_string() + ": " + h.state + " (" + h.since.to_string() + ")");
}}
let report = "";
for line in lines {{
    report += line + "\\n";
}}

let path = write_scratch_file("monitor-report.md", report);

// A stopped or blocked job with no confident cause is a human decision, not a retry.
if (verdict == "blocked" || verdict == "stopped") && (diagnosis == () || diagnosis.confidence == "low") {{
    complete(#{{ path: path, report: report, status: verdict, needs_human: true }});
}}

complete(#{{ path: path, report: report, status: verdict, needs_human: false }});
'''


def validate(script: str) -> list[str]:
    """Re-check what `meta.rs` would check, plus the lock contract."""
    problems: list[str] = []
    meta = re.match(r"^(?://[^\n]*\n)*let meta = #\{(.*?)\n\};", script, re.DOTALL)
    if not meta:
        return ["meta is not the first statement or is not a pure literal"]
    body = meta.group(1)

    name = re.search(r'name:\s*"([^"]*)"', body)
    if not name:
        problems.append("meta.name missing")
    else:
        n = name.group(1)
        if len(n.encode()) > MAX_NAME_BYTES:
            problems.append(f"name above {MAX_NAME_BYTES} bytes")
        if "--" in n:
            problems.append("name has a double hyphen")
        if not NAME_OK.match(n):
            problems.append("name is not lowercase/hyphen")

    desc = re.search(r'description:\s*"([^"]*)"', body)
    if not desc:
        problems.append("meta.description missing")
    elif len(desc.group(1)) > MAX_DESCRIPTION:
        problems.append(f"description above {MAX_DESCRIPTION}")

    wtu = re.search(r'when_to_use:\s*"([^"]*)"', body)
    if wtu and len(wtu.group(1)) > MAX_WHEN_TO_USE:
        problems.append(f"when_to_use above {MAX_WHEN_TO_USE}")

    titles = re.findall(r'title:\s*"([^"]*)"', body)
    if not titles:
        problems.append("meta.phases empty")
    if len(titles) > MAX_PHASES:
        problems.append(f"more than {MAX_PHASES} phases")
    if len(set(titles)) != len(titles):
        problems.append("duplicate phase titles")
    for t in titles:
        if len(t) > 128:
            problems.append(f"phase title over 128 chars: {t}")

    for used in set(re.findall(r'phase\("([^"]+)"\)', script)):
        if used not in titles:
            problems.append(f'phase("{used}") is not in meta.phases')
    for used in set(re.findall(r'phase:\s*"([^"]+)"', script)):
        if used not in titles:
            problems.append(f'agent phase "{used}" is not in meta.phases')

    if "cargo" in script and "NEVER run cargo" not in script:
        problems.append("mentions cargo without the lock contract")
    if script.count("capability_mode:") and "read-only" not in script:
        problems.append("agents are not read-only")
    if "complete(" not in script:
        problems.append("no complete() call")
    return problems


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--transport", default="native")
    parser.add_argument("--phases", type=int, default=4)
    args = parser.parse_args()
    OUT.mkdir(exist_ok=True)

    phases, phase_choices = choose_phases(INTENT, args.phases)
    with transports.Client.build(args.transport, timeout_s=60.0) as client:
        name_choice = choose_name(client)

    description = (
        "Watch a long-running job started in another session, detect when it stops or blocks, "
        "and report — read-only throughout, so it never takes the target-dev Cargo lock."
    )
    script = render(name_choice.picked, description, phases)
    problems = validate(script)
    target = target_for(name_choice.picked)
    target.write_text(script, encoding="utf-8")

    print(f"workflow gerado: {target.name}")
    print(f"  nome escolhido pelo jev: {name_choice.picked} (de {len(name_choice.alternatives)} alternativas)")
    print(f"  fases escolhidas por embedding+reranker: {', '.join(t for t, _ in phases)}")
    print(f"  bytes: {len(script)} | fases: {len(phases)}")
    print(f"  validação: {'limpa' if not problems else str(len(problems)) + ' problema(s)'}")
    for p in problems:
        print(f"    - {p}")

    (OUT / "workflow-generation.json").write_text(
        json.dumps(
            {
                "intent": INTENT,
                "name": asdict(name_choice),
                "phases": [asdict(c) for c in phase_choices],
                "problems": problems,
                "bytes": len(script),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"  -> {(OUT / 'workflow-generation.json').name}")


if __name__ == "__main__":
    main()