"""Memory scope and gate simulation.

Two questions the memory system currently answers badly or not at all:

1. **Scope** — for a candidate note, is it about *this folder*, about the *user*,
   or noise? Today everything drifts to global, which is exactly the confusion
   the folder-scoping is meant to stop.
2. **Keep/drop with the existing index in view** — the earlier gate scored 92%
   precision and 61% recall, and its single false positive was a duplicate the
   gate could not see because it never received the existing entries.

Arm B of experiment 2 tests that fix directly: same candidate, plus the current
memory entries in the state.

    python sim_memory_scope.py --transport native
"""

from __future__ import annotations

import argparse
import json
import statistics
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.table import Table

from jev import primitives, transports

ROOT = Path(__file__).parent
OUT = ROOT / "out"
PRICE_IN = 0.042
WORKERS = 8

WORKSPACE_PATH = "/Users/farchanjo/dev/grok-build"
STORE_THRESHOLD = 0.5

console = Console()

SCOPE_QUESTION = (
    "A note is being filed into long-term memory. Which bucket does it belong in? "
    "The agent is working in the folder given in the state."
)

SCOPE_CRITERIA = {
    "this_folder": (
        "True only of this repository: its layout, its conventions, a decision taken here, "
        "a command that works here and would not transfer to another project."
    ),
    "global": (
        "True of the user or the machine everywhere: a working preference, a tool they always "
        "use, a rule about how they want to be talked to, a credential location. Also a fact "
        "about a different project that this folder has no claim on."
    ),
    "discard": (
        "Momentary state, trivially rediscoverable, or already implied by something else."
    ),
}

GATE_QUESTION = (
    "This candidate note is being considered for long-term memory. Should it be stored, so a "
    "future session recalls it?"
)

# ── experiment 1: scope routing ────────────────────────────────────────────

SCOPE_CASES: list[dict[str, str]] = [
    # about this folder
    {"note": "In grok-build, validation goes through ./grok-check.sh and ./grok-test.sh, never raw cargo.", "gold": "this_folder"},
    {"note": "The dev profile for this repo is ~/.grokdev, and the leader socket lives there.", "gold": "this_folder"},
    {"note": "TUI verification in this repo runs in a detached tmux session named grok-dev.", "gold": "this_folder"},
    {"note": "xai-grok-pager-bin is the composition root; the released command is grok.", "gold": "this_folder"},
    {"note": "The repo's own target dir is ./target-dev and only one Cargo helper may run at a time.", "gold": "this_folder"},
    {"note": "Permissions, sandbox and session changes in this repo require failure-path tests, not just happy path.", "gold": "this_folder"},
    {"note": "The compaction jev knob in this repo defaults to off and fails open.", "gold": "this_folder"},
    {"note": "This repo keeps docs/ in sync with code changes.", "gold": "this_folder"},
    {"note": "Cargo.lock here is tracked and must not change for source-only edits.", "gold": "this_folder"},
    {"note": "The fcustom version lives lockstep in four manifests.", "gold": "this_folder"},
    # about the user, everywhere
    {"note": "The user prefers pt-BR in conversation and en-US in every artifact.", "gold": "global"},
    {"note": "Never pad verification commands with long sleeps; poll the state directly.", "gold": "global"},
    {"note": "For Grafana work, always go through the HTTP API, never the browser UI.", "gold": "global"},
    {"note": "Commits follow Angular convention, small and contextual.", "gold": "global"},
    {"note": "Never run make deploy unless the user asks explicitly.", "gold": "global"},
    {"note": "The user's long-lived API keys live in ~/.llm-key.", "gold": "global"},
    {"note": "The user uses uv for Python and pnpm for Node, never npm.", "gold": "global"},
    {"note": "Subagents are only dispatched on explicit opt-in, never by default.", "gold": "global"},
    {"note": "The user runs several agent sessions at once and expects them not to collide.", "gold": "global"},
    {"note": "Ask before destructive or externally visible actions.", "gold": "global"},
    {"note": "Jev cannot generate strings, so it decides and scores but never writes prose.", "gold": "global"},
    {"note": "The qwen-benchmark dashboard is generated by docker/obs/build-dashboard.py, never hand-edited.", "gold": "global"},
    # noise
    {"note": "The tree was clean at 21h40.", "gold": "discard"},
    {"note": "The last command exited 0.", "gold": "discard"},
    {"note": "httpx, pydantic, numpy and rich are installed in the venv.", "gold": "discard"},
    {"note": "The user said thanks.", "gold": "discard"},
    {"note": "The file has 350 lines.", "gold": "discard"},
    {"note": "The build took five minutes so far.", "gold": "discard"},
    {"note": "There are 172 skills in the profile.", "gold": "discard"},
    {"note": "The test has not run yet.", "gold": "discard"},
    {"note": "The folder is called script-test, with a hyphen.", "gold": "discard"},
    {"note": "A grep returned 69 matching lines.", "gold": "discard"},
    {"note": "The session id is 01a0b71b.", "gold": "discard"},
    {"note": "The other session is still running its nextest.", "gold": "discard"},
]

# ── experiment 2: gate, with and without the existing index ────────────────

EXISTING = [
    "The user prefers pt-BR in conversation and en-US in artifacts.",
    "Never pad verification commands with long sleeps; poll state directly.",
    "For Grafana work use the HTTP API, not the browser.",
    "The dev profile is ~/.grokdev with its own leader socket.",
]

GATE_CASES: list[dict[str, str]] = [
    {"note": "The user prefers pt-BR in conversation and en-US in artifacts.", "gold": "skip", "kind": "duplicate"},
    {"note": "Never use long sleep padding; poll the state instead of waiting.", "gold": "skip", "kind": "duplicate"},
    {"note": "Grafana changes go through the HTTP API, browser only for visual checks.", "gold": "skip", "kind": "duplicate"},
    {"note": "The dev profile for this repo is ~/.grokdev and the leader socket lives there.", "gold": "skip", "kind": "duplicate"},
    {"note": "The user prefers Portuguese in chat with English technical terms.", "gold": "skip", "kind": "duplicate-near"},
    {"note": "Avoid long sleeps when verifying, just re-check.", "gold": "skip", "kind": "duplicate-near"},
    {"note": "The user prefers responses in pt-BR.", "gold": "skip", "kind": "duplicate-near"},
    {"note": "TUI verification runs in a tmux session called grok-dev.", "gold": "store", "kind": "new"},
    {"note": "Validation in this repo goes through ./grok-check.sh and ./grok-test.sh.", "gold": "store", "kind": "new"},
    {"note": "The permission auto-mode classifier is the highest-leverage place for a decision model.", "gold": "store", "kind": "new"},
    {"note": "The Jev decisions endpoint accepts choice and score, verified by probe.", "gold": "store", "kind": "new"},
    {"note": "Skill selection has no natural-language eval cases at all.", "gold": "store", "kind": "new"},
    {"note": "The user keeps API keys in ~/.llm-key under export lines.", "gold": "store", "kind": "new"},
    {"note": "Commits follow Angular convention and stay small.", "gold": "store", "kind": "new"},
    {"note": "Cargo.lock must not change for source-only edits.", "gold": "store", "kind": "new"},
    {"note": "The user cancelled a command over a long sleep.", "gold": "skip", "kind": "momentary"},
    {"note": "The tree was clean at 21h40.", "gold": "skip", "kind": "momentary"},
    {"note": "The last command exited 0.", "gold": "skip", "kind": "momentary"},
    {"note": "The test has not run yet.", "gold": "skip", "kind": "momentary"},
    {"note": "The file has 350 lines.", "gold": "skip", "kind": "momentary"},
    {"note": "There are 172 skills in the profile.", "gold": "skip", "kind": "momentary"},
    {"note": "A grep returned 69 matching lines.", "gold": "skip", "kind": "momentary"},
    {"note": "The other session is still running its nextest.", "gold": "skip", "kind": "momentary"},
    {"note": "The venv has httpx and numpy installed.", "gold": "skip", "kind": "momentary"},
]


@dataclass
class Call:
    experiment: str
    arm: str
    case_id: str
    gold: str
    picked: str | None = None
    value: float | None = None
    correct: bool | None = None
    latency_ms: float = 0.0
    input_tokens: int = 0
    error: str = ""
    extra: dict[str, Any] = field(default_factory=dict)


def scope_state(note: str) -> dict[str, str]:
    return {"workspace_path": WORKSPACE_PATH, "repo": "grok-build", "candidate_note": note}


def gate_state(note: str, with_index: bool) -> dict[str, Any]:
    state: dict[str, Any] = {"candidate_note": note}
    if with_index:
        state["already_in_memory"] = "\n".join(f"- {e}" for e in EXISTING)
    return state


TIEBREAK = (
    " Tie-break: a fact about a different project is not this folder. Use this_folder only when "
    "the fact would be false in another repository; if it holds for the user or the machine "
    "anywhere, it is global."
)


def run_scope(client: transports.Client) -> list[Call]:
    cases = SCOPE_CASES
    results: list[Call | None] = [None] * len(cases)
    questions = {"bucket": primitives.choice(SCOPE_QUESTION, SCOPE_CRITERIA)}

    def one(index: int, arm: str = "plain") -> tuple[int, Call]:
        case = cases[index]
        call = Call("scope", arm, case["note"][:40], case["gold"])
        try:
            q = {"bucket": primitives.choice(SCOPE_QUESTION + (TIEBREAK if arm == "tiebreak" else ""), SCOPE_CRITERIA)}
            response = client.ask(scope_state(case["note"]), q)
        except transports.TransportError as error:
            call.error = str(error)
            return index, call
        call.latency_ms = response.latency_ms
        call.input_tokens = response.input_tokens
        call.picked = response.choice("bucket").choice
        call.extra["confidence"] = response.choice("bucket").confidence
        call.correct = call.picked == case["gold"]
        return index, call

    out: list[Call] = []
    for arm in ("plain", "tiebreak"):
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            for index, call in pool.map(lambda i, a=arm: one(i, a), range(len(cases))):
                results[index] = call
        out += [c for c in results if c is not None]
    return out


def run_gate(client: transports.Client) -> list[Call]:
    calls: list[Call] = []
    for arm, with_index in (("bare", False), ("with_index", True), ("decomposed", True)):
        questions = {
            "worth_recalling": primitives.noul(
                "Would this note still be worth recalling in a future session, on its own merits?",
                true="Durable fact, rule, preference, or verified result",
                false="Momentary state or trivially rediscoverable",
            ),
            "already_covered": primitives.noul(
                "Do the entries already in memory already say this, or something close enough that "
                "storing it again adds nothing?",
                true="Already said, or near enough that a second copy adds nothing",
                false="New: nothing above covers it",
            ),
        }

        def one(index: int, arm: str = arm, with_index: bool = with_index) -> tuple[int, Call]:
            case = GATE_CASES[index]
            call = Call("gate", arm, case["note"][:40], case["gold"], extra={"kind": case["kind"]})
            try:
                response = client.ask(gate_state(case["note"], with_index), questions)
            except transports.TransportError as error:
                call.error = str(error)
                return index, call
            call.latency_ms = response.latency_ms
            call.input_tokens = response.input_tokens
            call.value = response.noul("worth_recalling")
            covered = response.noul("already_covered")
            call.extra["covered"] = covered
            if arm == "decomposed":
                call.picked = "store" if (call.value >= STORE_THRESHOLD and covered < STORE_THRESHOLD) else "skip"
            else:
                call.picked = "store" if call.value >= STORE_THRESHOLD else "skip"
            call.correct = call.picked == case["gold"]
            return index, call

        results: list[Call | None] = [None] * len(GATE_CASES)
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            for index, call in pool.map(one, range(len(GATE_CASES))):
                results[index] = call
        calls += [c for c in results if c is not None]
    return calls


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--transport", default="native")
    args = parser.parse_args()
    OUT.mkdir(exist_ok=True)

    all_calls: list[Call] = []
    with transports.Client.build(args.transport, timeout_s=60.0) as client:
        all_calls += run_scope(client)
        all_calls += run_gate(client)

    console.rule(f"memory — {args.transport}")

    scope = [c for c in all_calls if c.experiment == "scope" and not c.error]
    table = Table(title="experiment 1: scope routing")
    table.add_column("gold")
    table.add_column("n", justify="right")
    table.add_column("correct", justify="right")
    for bucket in ("this_folder", "global", "discard"):
        subset = [c for c in scope if c.gold == bucket and c.arm == "plain"]
        hits = sum(1 for c in subset if c.correct)
        table.add_row(bucket, str(len(subset)), f"{hits}/{len(subset)}")
    for arm in ("plain", "tiebreak"):
        a = [c for c in scope if c.arm == arm]
        table.add_row(f"overall [{arm}]", str(len(a)), f"{sum(1 for c in a if c.correct) / len(a):.1%}")
    console.print(table)

    confusion: dict[tuple[str, str], int] = {}
    for call in scope:
        if call.picked != call.gold:
            confusion[(call.gold, call.picked or "-")] = confusion.get((call.gold, call.picked or "-"), 0) + 1
    console.print("  confusions (gold -> picked):", dict(sorted(confusion.items())))

    gate = [c for c in all_calls if c.experiment == "gate" and not c.error]
    table = Table(title="experiment 2: keep/drop gate")
    for column in ("arm", "n", "accuracy", "precision", "recall", "dupes caught", "p50 ms"):
        table.add_column(column, justify="right" if column != "arm" else "left")
    for arm in ("bare", "with_index", "decomposed"):
        subset = [c for c in gate if c.arm == arm]
        tp = sum(1 for c in subset if c.gold == "store" and c.picked == "store")
        fn = sum(1 for c in subset if c.gold == "store" and c.picked == "skip")
        fp = sum(1 for c in subset if c.gold == "skip" and c.picked == "store")
        tn = sum(1 for c in subset if c.gold == "skip" and c.picked == "skip")
        dupes = [c for c in subset if c.extra.get("kind", "").startswith("duplicate")]
        table.add_row(
            arm,
            str(len(subset)),
            f"{(tp + tn) / len(subset):.1%}",
            f"{tp / (tp + fp):.1%}" if tp + fp else "-",
            f"{tp / (tp + fn):.1%}" if tp + fn else "-",
            f"{sum(1 for c in dupes if c.picked == 'skip')}/{len(dupes)}",
            f"{statistics.median([c.latency_ms for c in subset]):.0f}",
        )
    console.print(table)

    for arm in ("bare", "with_index", "decomposed"):
        wrong = [
            c for c in gate if c.arm == arm and c.gold == "store" and c.picked == "skip"
        ]
        console.print(f"  {arm}: dropped but worth keeping ({len(wrong)}):")
        for call in wrong[:6]:
            console.print(f"    {call.value:.2f}  {call.case_id}")

    raw = OUT / f"results-memory-{args.transport}.jsonl"
    with raw.open("w", encoding="utf-8") as handle:
        for call in all_calls:
            handle.write(json.dumps(asdict(call), ensure_ascii=False) + "\n")
    tokens = sum(c.input_tokens for c in all_calls)
    console.print(f"\n{len(all_calls)} calls, {tokens:,} tokens, ${tokens / 1e6 * PRICE_IN:.4f} -> {raw.relative_to(ROOT)}")


if __name__ == "__main__":
    main()