"""End-to-end memory pipeline: today's behaviour vs today plus Jev, same events.

The stages a memory system needs, and what each does today:

| stage | today | with Jev |
| --- | --- | --- |
| capture / admission | nothing is gated, everything is written | one gate, index in state |
| scope routing | everything drifts to global | routed workspace / global |
| dedup at write | none, duplicates pile up | checked against the store |
| retrieval | FTS + dense + RRF | same, unchanged |
| rerank | the profile's `reranker_models` is empty | Jev reranks the shortlist |

Nothing is removed: the retrieval half is byte-identical in both arms, and the
only difference is what got admitted, where it landed, and whether the shortlist
is reranked.

The event stream is 48 notes from a session working in this repository, mixed
with notes about other projects and with noise. Twelve later queries then ask
the store for things, from this workspace. Metrics are end-to-end: what the store
kept, where it filed it, and what the queries get back.

    python sim_memory_pipeline.py --transport native
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sqlite3
import statistics
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import httpx
from rich.console import Console
from rich.table import Table

from jev import primitives, transports

ROOT = Path(__file__).parent
OUT = ROOT / "out"
CACHE = OUT / "embeddings.json"
PRICE_IN = 0.042
WORKERS = 8
RRF_K = 60
SHORTLIST = 10
ADMIT_THRESHOLD = 0.25
COVERED_THRESHOLD = 0.50
WORKSPACE_PATH = "/Users/farchanjo/dev/grok-build"
EMBED_MODEL = "openai/text-embedding-3-small"
EMBED_URL = "https://openrouter.ai/api/v1/embeddings"

console = Console()

# ── the event stream: what a session would produce ─────────────────────────

@dataclass
class Event:
    text: str
    keep: bool
    scope: str  # "workspace" | "global" | "none" when keep is False
    project: str = "grok-build"
    dupe: bool = False


EVENTS: list[Event] = [
    # worth keeping, about this folder
    Event("Validation in this repo goes through ./grok-check.sh and ./grok-test.sh, never raw cargo.", True, "workspace"),
    Event("The dev profile is ~/.grokdev and its leader socket lives there; never touch ~/.grok.", True, "workspace"),
    Event("TUI verification runs in a detached tmux session named grok-dev, killed when done.", True, "workspace"),
    Event("One Cargo helper at a time against ./target-dev; waiting on the lock is expected.", True, "workspace"),
    Event("Cargo.lock is tracked and must not change for source-only edits.", True, "workspace"),
    Event("The fcustom version lives lockstep in four manifests and uses plain semver.", True, "workspace"),
    Event("make deploy is not part of the ordinary edit loop; it needs an explicit request.", True, "workspace"),
    Event("Permission, sandbox and session changes in this repo need failure-path tests.", True, "workspace"),
    Event("The repo keeps docs/ in sync with code changes.", True, "workspace"),
    Event("xai-grok-pager-bin is the composition root; the released command is grok.", True, "workspace"),
    Event("The permission auto-mode classifier is the highest-leverage place for a decision model.", True, "workspace"),
    Event("Skill selection has no natural-language eval cases; only resource and explicit_pin exist.", True, "workspace"),
    # worth keeping, about the user anywhere
    Event("The user prefers pt-BR in conversation and en-US in every artifact.", True, "global"),
    Event("Never pad verification commands with long sleeps; poll the state directly.", True, "global"),
    Event("For Grafana work always use the HTTP API; the browser is only for visual checks.", True, "global"),
    Event("Commits follow Angular convention, small and contextual.", True, "global"),
    Event("Never run make deploy unless the user asks explicitly.", True, "global"),
    Event("The user's long-lived API keys live in ~/.llm-key.", True, "global"),
    Event("The user uses uv for Python and pnpm for Node, never npm.", True, "global"),
    Event("Subagents are only dispatched on explicit opt-in, never by default.", True, "global"),
    Event("Ask before destructive or externally visible actions.", True, "global"),
    Event("The user runs several agent sessions at once and expects them not to collide.", True, "global"),
    Event("Jev cannot generate strings: it decides and scores, never writes prose.", True, "global"),
    Event("The Jev decisions endpoint accepts choice and score, verified by probe.", True, "global"),
    # worth keeping, about another project (so: global from here)
    Event("The qwen-benchmark dashboard JSON is generated by docker/obs/build-dashboard.py, never hand-edited.", True, "global", "qwen"),
    Event("The flashnext Grafana lives at grafana.flashnext.model.craton.app and needs GRAFANA_ADMIN_PASSWORD.", True, "global", "flashnext"),
    Event("In the detent project, services are declared in detent.json and lifecycle calls are idempotent.", True, "global", "detent"),
    Event("The urls-code project keys everything by content hash, never by path.", True, "global", "urls-code"),
    # duplicates of earlier ones, as a session would restate them
    Event("In this repo tests go through grok-test.sh, not cargo test directly.", True, "workspace", dupe=True),
    Event("The dev profile for local work is ~/.grokdev with its own socket.", True, "workspace", dupe=True),
    Event("Keep verification commands short, avoid sleep padding, poll instead.", True, "global", dupe=True),
    Event("Grafana changes go through the HTTP API rather than clicking in the browser.", True, "global", dupe=True),
    Event("The user wants answers in Portuguese with English technical terms.", True, "global", dupe=True),
    Event("API keys are kept in ~/.llm-key.", True, "global", dupe=True),
    Event("Use uv for Python, pnpm for Node.", True, "global", dupe=True),
    Event("Commit style is Angular, small commits.", True, "global", dupe=True),
    # noise: momentary, rediscoverable
    Event("The tree was clean at 21h40.", False, "none"),
    Event("The last command exited 0.", False, "none"),
    Event("The venv has httpx, pydantic, numpy and rich installed.", False, "none"),
    Event("The user said thanks.", False, "none"),
    Event("The file has 350 lines.", False, "none"),
    Event("The build has been running for five minutes.", False, "none"),
    Event("There are 172 skills in the profile.", False, "none"),
    Event("The test has not run yet.", False, "none"),
    Event("The session id is 01a0b71b.", False, "none"),
    Event("A grep returned 69 matching lines.", False, "none"),
    Event("The other session is still running its nextest.", False, "none"),
    Event("The embeddings cache holds 238 vectors.", False, "none"),
]

QUERIES: list[dict[str, str]] = [
    {"q": "how do I run the tests here?", "gold": "Validation in this repo goes through ./grok-check.sh and ./grok-test.sh, never raw cargo.", "kind": "local"},
    {"q": "which profile does a dev build use?", "gold": "The dev profile is ~/.grokdev and its leader socket lives there; never touch ~/.grok.", "kind": "local"},
    {"q": "how do I check the TUI interactively?", "gold": "TUI verification runs in a detached tmux session named grok-dev, killed when done.", "kind": "local"},
    {"q": "can two cargo builds run at once?", "gold": "One Cargo helper at a time against ./target-dev; waiting on the lock is expected.", "kind": "local"},
    {"q": "does Cargo.lock change on a source-only edit?", "gold": "Cargo.lock is tracked and must not change for source-only edits.", "kind": "local"},
    {"q": "how do I bump the fcustom version?", "gold": "The fcustom version lives lockstep in four manifests and uses plain semver.", "kind": "local"},
    {"q": "what should I do before verifying a reload?", "gold": "Never pad verification commands with long sleeps; poll the state directly.", "kind": "global"},
    {"q": "how should I read a Grafana panel?", "gold": "For Grafana work always use the HTTP API; the browser is only for visual checks.", "kind": "global"},
    {"q": "which package manager for Node?", "gold": "The user uses uv for Python and pnpm for Node, never npm.", "kind": "global"},
    {"q": "where do the long-lived keys live?", "gold": "The user's long-lived API keys live in ~/.llm-key.", "kind": "global"},
    {"q": "who generates the qwen dashboard?", "gold": "The qwen-benchmark dashboard JSON is generated by docker/obs/build-dashboard.py, never hand-edited.", "kind": "other"},
    {"q": "how are detent services declared?", "gold": "In the detent project, services are declared in detent.json and lifecycle calls are idempotent.", "kind": "other"},
]

GATE_QUESTION = "Would this note still be worth recalling in a future session, on its own merits?"
GATE_TRUE = "Durable fact, rule, preference, or verified result"
GATE_FALSE = "Momentary state or trivially rediscoverable"
COVERED_QUESTION = (
    "Do the entries already in memory already say this, or something close enough that storing "
    "it again adds nothing?"
)
SCOPE_QUESTION = "Which bucket does this note belong in? The agent works in the folder given in the state."
SCOPE_CRITERIA = {
    "this_folder": "True only of this repository; it would be false elsewhere.",
    "global": "True of the user or the machine anywhere, or a fact about a different project.",
    "discard": "Momentary or rediscoverable.",
}
RERANK_QUESTION = (
    "The user is working in the folder given in the state. Is this memory one they would want "
    "surfaced for the query below?"
)
RERANK_TRUE = "It answers the query and applies where they are working."
RERANK_FALSE = "Only topically near, or about a different project and the query is about this one."


# ── retrieval helpers (identical in both arms) ─────────────────────────────

def embed_key() -> str:
    for path in ("~/.grokdev/auth.json", "~/.grok/auth.json"):
        p = Path(path).expanduser()
        if not p.is_file():
            continue
        store = json.loads(p.read_text(encoding="utf-8"))
        for scope in ("openai_compatible::prime-embeddings::api_key", "openrouter::api_key"):
            value = store.get(scope)
            if isinstance(value, dict) and value.get("key"):
                return value["key"]
            if isinstance(value, str) and value:
                return value
    raise RuntimeError("no embedding credential")


def cached(texts: list[str], key: str, namespace: str) -> list[list[float]]:
    cache = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.is_file() else {}
    missing = [t for t in texts if f"{namespace}:{hashlib.sha1(t.encode()).hexdigest()}" not in cache]
    if missing:
        with httpx.Client(timeout=120.0) as http:
            r = http.post(
                EMBED_URL,
                headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                json={"model": EMBED_MODEL, "input": missing},
            )
            r.raise_for_status()
            for text, item in zip(missing, r.json()["data"]):
                cache[f"{namespace}:{hashlib.sha1(text.encode()).hexdigest()}"] = item["embedding"]
        OUT.mkdir(exist_ok=True)
        CACHE.write_text(json.dumps(cache), encoding="utf-8")
    return [cache[f"{namespace}:{hashlib.sha1(t.encode()).hexdigest()}"] for t in texts]


def cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    return dot / ((math.sqrt(sum(x * x for x in a)) or 1.0) * (math.sqrt(sum(y * y for y in b)) or 1.0))


def bm25(texts: list[str], query: str, limit: int) -> list[int]:
    db = sqlite3.connect(":memory:")
    db.execute("CREATE VIRTUAL TABLE m USING fts5(t)")
    db.executemany("INSERT INTO m (t) VALUES (?)", [(t,) for t in texts])
    terms = " OR ".join(re.findall(r"[A-Za-z0-9_]{3,}", query.lower()) or ["a"])
    rows = db.execute("SELECT rowid FROM m WHERE m MATCH ? ORDER BY bm25(m) LIMIT ?", (terms, limit)).fetchall()
    db.close()
    # FTS5 rowids are 1-based; the store is a plain list.
    return [r[0] - 1 for r in rows]


def retrieve(store: list[str], vectors: list[list[float]], query: str, qvec: list[float], limit: int) -> list[int]:
    """FTS + dense + weighted RRF — the half that never changes."""
    lexical = bm25(store, query, limit)
    dense = [i for _, i in sorted(((cosine(qvec, v), i) for i, v in enumerate(vectors)), key=lambda kv: -kv[0])[:limit]]
    scores: dict[int, float] = {}
    for ranking in (lexical, dense):
        for position, index in enumerate(ranking, start=1):
            scores[index] = scores.get(index, 0.0) + 1.0 / (RRF_K + position)
    return [i for i, _ in sorted(scores.items(), key=lambda kv: -kv[1])[:limit]]


# ── the two pipelines ──────────────────────────────────────────────────────

@dataclass
class Result:
    arm: str
    stored: int = 0
    kept_right: int = 0
    dropped_wrong: int = 0
    duplicates_stored: int = 0
    dupes_caught: int = 0
    noise_slipped: int = 0
    scope_confusions: dict = field(default_factory=dict)
    scope_right: int = 0
    scope_wrong: int = 0
    top1: int = 0
    top1_no_rerank: int = 0
    in_top10: int = 0
    pollution: int = 0
    queries: int = 0
    latency_ms: float = 0.0
    tokens: int = 0
    detail: list[dict[str, Any]] = field(default_factory=list)


def run_jev_stages(client: transports.Client) -> tuple[list[Event], Result, list[str]]:
    """Admission, dedup and scope routing, all with the store in the state.

    Accounting is explicit per event so a dropped restatement is never counted
    as a loss, and a dropped valuable note never hides inside a dupe count.
    """
    result = Result("today + jev")
    admitted: list[Event] = []
    store_texts: list[str] = []

    for event in EVENTS:
        state: dict[str, Any] = {
            "candidate_note": event.text,
            "workspace_path": WORKSPACE_PATH,
            "already_in_memory": "\n".join(f"- {t}" for t in store_texts) or "(empty)",
        }
        response = client.ask(
            state,
            {
                "worth": primitives.noul(GATE_QUESTION, true=GATE_TRUE, false=GATE_FALSE),
                "covered": primitives.noul(COVERED_QUESTION),
            },
        )
        result.tokens += response.input_tokens
        result.latency_ms += response.latency_ms
        worth = response.noul("worth")
        covered = response.noul("covered")

        if covered >= COVERED_THRESHOLD:
            # A restatement being refused is the win this stage exists for.
            if event.dupe:
                result.dupes_caught += 1
            elif event.keep:
                result.dropped_wrong += 1
            else:
                result.kept_right += 1
            continue
        if worth < ADMIT_THRESHOLD:
            if event.keep and not event.dupe:
                result.dropped_wrong += 1
            elif event.dupe:
                result.dupes_caught += 1
            else:
                result.kept_right += 1
            continue

        bucket = "workspace"
        if event.keep:
            scope_response = client.ask(
                {"workspace_path": WORKSPACE_PATH, "candidate_note": event.text},
                {"bucket": primitives.choice(SCOPE_QUESTION, SCOPE_CRITERIA)},
            )
            result.tokens += scope_response.input_tokens
            result.latency_ms += scope_response.latency_ms
            bucket = scope_response.choice("bucket").choice
            if bucket == "discard":
                if event.dupe:
                    result.dupes_caught += 1
                else:
                    result.dropped_wrong += 1
                continue
            # The criteria key is `this_folder`; the labels say `workspace`.
            bucket = "workspace" if bucket == "this_folder" else bucket
            if bucket == event.scope:
                result.scope_right += 1
            else:
                result.scope_wrong += 1
                key = f"{event.scope}->{bucket}"
                result.scope_confusions[key] = result.scope_confusions.get(key, 0) + 1

        if not event.keep:
            result.noise_slipped += 1
        elif event.dupe:
            result.duplicates_stored += 1
        admitted.append(event)
        store_texts.append(event.text)
        result.stored += 1

    return admitted, result, store_texts


def run_today() -> tuple[list[Event], Result, list[str]]:
    """No gate, no dedup, everything global."""
    result = Result("today")
    texts = [e.text for e in EVENTS]
    result.stored = len(EVENTS)
    result.duplicates_stored = sum(1 for e in EVENTS if e.dupe)
    return list(EVENTS), result, texts


def run_queries(
    arm: str,
    store: list[str],
    result: Result,
    key: str,
    client: transports.Client | None,
) -> None:
    vectors = cached(store, key, f"store:{arm}")
    qvecs = cached([q["q"] for q in QUERIES], key, "query")
    for case, qvec in zip(QUERIES, qvecs):
        hits = retrieve(store, vectors, case["q"], qvec, SHORTLIST)
        top = hits[0] if hits else None
        result.queries += 1
        if top is not None and store[top] == case["gold"]:
            result.top1 += 1
        if case["gold"] in [store[i] for i in hits]:
            result.in_top10 += 1
        if client is not None and hits:
            shortlist = [store[i] for i in hits]
            response = client.ask(
                {"workspace_path": WORKSPACE_PATH, "query": case["q"]},
                {
                    f"cand::{i}": primitives.noul(
                        f"{RERANK_QUESTION}\n\nChunk (scope: {'workspace' if i < len(store) else 'global'}): {text}",
                        true=RERANK_TRUE,
                        false=RERANK_FALSE,
                    )
                    for i, text in enumerate(shortlist)
                },
            )
            result.tokens += response.input_tokens
            result.latency_ms += response.latency_ms
            scored = sorted(
                ((response.noul(f"cand::{i}"), text) for i, text in enumerate(shortlist)),
                key=lambda kv: -kv[0],
            )
            top = scored[0][1] if scored else None
            if top == case["gold"]:
                result.top1 += 0  # recomputed below
        result.detail.append({"q": case["q"], "gold": case["gold"], "kind": case["kind"], "base_top1": store[top] if top is not None else None})


def rerank_arm(store: list[str], result: Result, key: str, client: transports.Client) -> None:
    """Recompute top-1 with the rerank applied, and count pollution."""
    vectors = cached(store, key, f"store:{result.arm}")
    qvecs = cached([q["q"] for q in QUERIES], key, "query")
    result.top1 = 0
    result.pollution = 0
    for case, qvec in zip(QUERIES, qvecs):
        hits = retrieve(store, vectors, case["q"], qvec, SHORTLIST)
        shortlist = [store[i] for i in hits]
        response = client.ask(
            {"workspace_path": WORKSPACE_PATH, "query": case["q"]},
            {
                f"cand::{i}": primitives.noul(
                    f"{RERANK_QUESTION}\n\nChunk: {text}",
                    true=RERANK_TRUE,
                    false=RERANK_FALSE,
                )
                for i, text in enumerate(shortlist)
            },
        )
        result.tokens += response.input_tokens
        result.latency_ms += response.latency_ms
        scored = sorted(((response.noul(f"cand::{i}"), t) for i, t in enumerate(shortlist)), key=lambda kv: -kv[0])
        top = scored[0][1] if scored else None
        if top == case["gold"]:
            result.top1 += 1
        match = next((e for e in EVENTS if e.text == top), None)
        if case["kind"] == "local" and match is not None:
            if match.project != "grok-build" or not match.keep:
                result.pollution += 1


def report(results: list[Result]) -> None:
    table = Table(title="memory pipeline, end to end — 48 events, 12 later queries")
    for column in ("metric", *[r.arm for r in results]):
        table.add_column(column, justify="right" if column != "metric" else "left")
    rows = [
        ("notes stored", lambda r: f"{r.stored}"),
        ("noise correctly dropped", lambda r: f"{r.kept_right}"),
        ("valuable dropped (loss)", lambda r: f"{r.dropped_wrong}"),
        ("duplicate restatements stored", lambda r: f"{r.duplicates_stored}"),
        ("scope routed right", lambda r: f"{r.scope_right}"),
        ("scope routed wrong", lambda r: f"{r.scope_wrong} {r.scope_confusions or ''}"),
        ("valuable notes lost", lambda r: f"{r.dropped_wrong}"),
        ("duplicates correctly not re-stored", lambda r: f"{r.dupes_caught}"),
        ("noise that slipped through", lambda r: f"{r.noise_slipped}"),
        ("query top-1 (no rerank)", lambda r: f"{r.top1_no_rerank}/{r.queries}"),
        ("query top-1 (reranked)", lambda r: f"{r.top1}/{r.queries}"),
        ("gold in top-10", lambda r: f"{r.in_top10}/{r.queries}"),
        ("cross-project pollution", lambda r: f"{r.pollution}/{r.queries}"),
        ("tokens", lambda r: f"{r.tokens:,}"),
    ]
    for name, getter in rows:
        table.add_row(name, *[getter(r) for r in results])
    console.print(table)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--transport", default="native")
    args = parser.parse_args()
    OUT.mkdir(exist_ok=True)
    key = embed_key()

    started = time.time()
    with transports.Client.build(args.transport, timeout_s=60.0) as client:
        today_events, today, today_store = run_today()
        jev_events, jev, jev_store = run_jev_stages(client)

        # baseline retrieval for both arms, no rerank
        for arm, store, result in (("today", today_store, today), ("today + jev", jev_store, jev)):
            vectors = cached(store, key, f"store:{arm}")
            qvecs = cached([q["q"] for q in QUERIES], key, "query")
            result.top1 = 0
            result.in_top10 = 0
            for case, qvec in zip(QUERIES, qvecs):
                hits = retrieve(store, vectors, case["q"], qvec, SHORTLIST)
                if hits and store[hits[0]] == case["gold"]:
                    result.top1 += 1
                if case["gold"] in [store[i] for i in hits]:
                    result.in_top10 += 1
            result.top1_no_rerank = result.top1
            result.queries = len(QUERIES)

        rerank_arm(today_store, today, key, client)
        rerank_arm(jev_store, jev, key, client)

    today.arm = "today"
    jev.arm = "today + jev"
    report([today, jev])

    console.print(f"\n  wall {time.time() - started:.0f}s, jev tokens {jev.tokens:,}, "
                  f"${jev.tokens / 1e6 * PRICE_IN:.4f}")
    raw = OUT / "results-memory-pipeline.jsonl"
    with raw.open("w", encoding="utf-8") as handle:
        for result in (today, jev):
            handle.write(json.dumps(asdict(result), ensure_ascii=False) + "\n")
    console.print(f"  -> {raw.relative_to(ROOT)}")


if __name__ == "__main__":
    main()