"""Memory retrieval rerank simulation.

The leak found on disk: the global `MEMORY.md` is indexed into every workspace at
weight 1.0, and the search tool has no scope parameter. This asks whether a
rerank fixes it — and specifically whether a rerank that knows the workspace
prefers local memory when the query is local, without losing global recall.

Baseline is keyword overlap, standing in for the BM25/FTS half of the real
hybrid search. Jev asks one `noul` per candidate, in isolation, and the code
sorts by it. Corpus is the profile's three real global memories plus workspace
and session chunks for this repository.

    python sim_memory_rerank.py --transport native
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.table import Table

from jev import primitives, transports

ROOT = Path(__file__).parent
OUT = ROOT / "out"
PRICE_IN = 0.042
WORKERS = 8
WORKSPACE_PATH = "/Users/farchanjo/dev/grok-build"

console = Console()

QUESTION = (
    "The user is working in the folder given in the state. Is this memory chunk one they would "
    "want surfaced for the query below?"
)
CRITERIA_TRUE = "It answers the query, and it applies where the user is working right now."
CRITERIA_FALSE = (
    "It is only topically near, or it is about a different project and the query is about this one."
)

# ── corpus: real global memories + workspace and session chunks ────────────

CORPUS: list[dict[str, str]] = [
    {
        "id": "g:sleeps",
        "scope": "global",
        "text": "Never pad verification commands with long sleep waits. The user cancelled a "
        "command over a 35s sleep. Query the state immediately and retry only if stale.",
    },
    {
        "id": "g:grafana",
        "scope": "global",
        "text": "For Grafana work always use the HTTP API, dashboards via /api/dashboards/uid, "
        "data via the datasource proxy. The browser is only for visual checks.",
    },
    {
        "id": "g:qwen",
        "scope": "global",
        "text": "The qwen-benchmark dashboard JSON is generated by docker/obs/build-dashboard.py. "
        "Never hand-edit qwen38-vllm.json; edit the generator and redeploy.",
    },
    {"id": "w:check", "scope": "workspace", "text": "Validation in this repo goes through ./grok-check.sh and ./grok-test.sh, never raw cargo."},
    {"id": "w:grokdev", "scope": "workspace", "text": "The dev profile is ~/.grokdev and the leader socket lives there; never touch ~/.grok."},
    {"id": "w:tmux", "scope": "workspace", "text": "TUI verification in this repo runs in a detached tmux session named grok-dev, then is killed."},
    {"id": "w:lock", "scope": "workspace", "text": "One Cargo helper at a time against ./target-dev; waiting on the lock is expected."},
    {"id": "w:lockfile", "scope": "workspace", "text": "Cargo.lock is tracked and must not change for source-only edits."},
    {"id": "w:version", "scope": "workspace", "text": "The fcustom version lives lockstep in four manifests and uses plain semver."},
    {"id": "w:deploy", "scope": "workspace", "text": "make deploy is not part of the ordinary edit loop; it needs an explicit request."},
    {"id": "w:security", "scope": "workspace", "text": "Permission, sandbox and session changes in this repo need failure-path tests."},
    {"id": "s:run1", "scope": "session", "text": "This session created script-test with a Python 3.14 venv and a two-transport Jev client."},
    {"id": "s:run2", "scope": "session", "text": "The other session committed MCP owner-routing work and is running nextest."},
    {"id": "s:run3", "scope": "session", "text": "The permission classifier agreed with the house policy on 89.8% of 127 commands."},
    {"id": "s:run4", "scope": "session", "text": "Stage two of the skill selector made accuracy worse on this roster."},
]

QUERIES: list[dict[str, Any]] = [
    {"q": "how do I run the tests in this repo?", "gold": "w:check"},
    {"q": "which profile should a dev build use?", "gold": "w:grokdev"},
    {"q": "how do I check the TUI interactively?", "gold": "w:tmux"},
    {"q": "can I run two cargo helpers at once?", "gold": "w:lock"},
    {"q": "does Cargo.lock change on a source-only edit?", "gold": "w:lockfile"},
    {"q": "how do I bump the fcustom version?", "gold": "w:version"},
    {"q": "should I run make deploy after every change?", "gold": "w:deploy"},
    {"q": "what do I do before verifying a config reload?", "gold": "g:sleeps"},
    {"q": "how should I read a Grafana panel value?", "gold": "g:grafana"},
    {"q": "who generates the qwen dashboard json?", "gold": "g:qwen"},
]

WORD = re.compile(r"[a-z0-9_]{3,}")


def tokens(text: str) -> set[str]:
    return set(WORD.findall(text.lower()))


def keyword_rank(query: str, corpus: list[dict[str, str]]) -> list[str]:
    qt = tokens(query)
    scored = [(len(qt & tokens(c["text"])) / (len(qt) or 1), c["id"]) for c in corpus]
    return [cid for _, cid in sorted(scored, key=lambda kv: -kv[0])]


@dataclass
class Row:
    query: str
    gold: str
    baseline_top1: str
    jev_top1: str | None = None
    jev_correct: bool | None = None
    baseline_correct: bool | None = None
    latency_ms: float = 0.0
    input_tokens: int = 0
    error: str = ""
    extra: dict[str, Any] = field(default_factory=dict)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--transport", default="native")
    args = parser.parse_args()
    OUT.mkdir(exist_ok=True)

    rows: list[Row | None] = [None] * len(QUERIES)

    def one(index: int) -> tuple[int, Row]:
        case = QUERIES[index]
        base = keyword_rank(case["q"], CORPUS)
        row = Row(
            query=case["q"],
            gold=case["gold"],
            baseline_top1=base[0],
            baseline_correct=base[0] == case["gold"],
        )
        state = {"workspace_path": WORKSPACE_PATH, "query": case["q"]}
        questions = {
            f"cand::{c['id']}": primitives.noul(
                f"{QUESTION}\n\nChunk (scope: {c['scope']}): {c['text']}",
                true=CRITERIA_TRUE,
                false=CRITERIA_FALSE,
            )
            for c in CORPUS
        }
        try:
            response = client.ask(state, questions)
        except transports.TransportError as error:
            row.error = str(error)
            return index, row
        row.latency_ms = response.latency_ms
        row.input_tokens = response.input_tokens
        scored = sorted(
            ((response.noul(f"cand::{c['id']}"), c["id"]) for c in CORPUS), key=lambda kv: -kv[0]
        )
        row.jev_top1 = scored[0][1]
        row.jev_correct = row.jev_top1 == case["gold"]
        row.extra["top3"] = [cid for _, cid in scored[:3]]
        row.extra["gold_score"] = next(s for s, cid in scored if cid == case["gold"])
        return index, row

    with transports.Client.build(args.transport, timeout_s=60.0) as client:
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            for index, row in pool.map(one, range(len(QUERIES))):
                rows[index] = row
    result = [r for r in rows if r is not None]

    console.rule(f"memory rerank — {args.transport}")
    table = Table()
    for column in ("metric", "keyword baseline", "jev rerank"):
        table.add_column(column)
    b = sum(1 for r in result if r.baseline_correct)
    j = sum(1 for r in result if r.jev_correct)
    table.add_row("top-1 correct", f"{b}/{len(result)}", f"{j}/{len(result)}")
    table.add_row("gold in top-3", "-", f"{sum(1 for r in result if r.gold in r.extra.get('top3', []))}/{len(result)}")
    table.add_row("p50 ms", "-", f"{statistics.median([r.latency_ms for r in result]):.0f}")
    console.print(table)

    console.print("\nper query:")
    for row in result:
        mark = "[green]OK[/green]" if row.jev_correct else "[red]ERR[/red]"
        base_mark = "ok" if row.baseline_correct else "err"
        console.print(
            f"  {mark} base={base_mark} gold={row.gold:<10} jev={row.jev_top1:<10} "
            f"gold_score={row.extra.get('gold_score', 0):.2f}  {row.query}"
        )

    raw = OUT / f"results-memory-rerank-{args.transport}.jsonl"
    with raw.open("w", encoding="utf-8") as handle:
        for row in result:
            handle.write(json.dumps(asdict(row), ensure_ascii=False) + "\n")
    console.print(f"\n-> {raw.relative_to(ROOT)}")


if __name__ == "__main__":
    main()