[package]
license = "Apache-2.0"
name = "xai-tracing-macros"
version = "0.1.0"
edition.workspace = true
description = "Tracing-based utility macros for timestamped logging and timing"

repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]

[lints]
workspace = true
