//! Milvus backend for the store-agnostic [`VectorMirror`] seam.
//!
//! [`MilvusStore`] wraps the official `milvus-sdk-rust` V2 client
//! (`ClientV2`, tonic gRPC) against a self-hosted standalone/server. The
//! bearer token lives only inside this struct — it is never logged, never
//! rendered by `Debug`, never persisted, and is redacted out of any error
//! detail this backend produces ([`crate::mirror::MirrorError`]).
//!
//! ## Collection contract
//!
//! - Schema: `id` VARCHAR primary key (no auto-id, so upserts are
//!   idempotent), `embedding` FLOAT_VECTOR(dims), `fp` VARCHAR carrying the
//!   installed fingerprint hash.
//! - Metric `IP` over unit-L2 vectors; distances are converted to the
//!   sqlite-vec L2 contract via
//!   [`crate::mirror::similarity_to_l2_distance`] (`2·(1 − sim)`).
//! - Index `AUTOINDEX`; the fingerprint/dims/schema tag is stored in the
//!   collection description and verified on attach — a mismatch or absent
//!   tag drops and recreates the collection (the resync engine then
//!   repopulates it from SQLite).

use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use milvus::v2::error::Error;
use milvus::v2::request::collection::{
    CreateCollectionRequest, DescribeCollectionRequest, DropCollectionRequest,
    HasCollectionRequest, LoadCollectionRequest,
};
use milvus::v2::request::dml::{DeleteRequest, InsertRequest, UpsertRequest};
use milvus::v2::request::dql::{QueryRequest, SearchRequest};
use milvus::v2::types::{
    CollectionSchema, DataType, FieldData, FieldSchema, Function, FunctionType, Ids, IndexParam,
    IndexType, MetricType, RetryConfig, SearchVectors,
};
use milvus::v2::{ClientV2, ConnectConfig};

use crate::mirror::{
    MirrorError, MirrorErrorKind, VectorMirror, collection_tag, parse_collection_tag,
    similarity_to_l2_distance, MemoryRow, RemoteSearchHit, MEMORY_SCHEMA_VERSION_V2,
};

/// Name of the VARCHAR primary-key field (`id`).
const FIELD_ID: &str = "id";
/// Name of the VARCHAR text field (`text`) with analyzer enabled.
const FIELD_TEXT: &str = "text";
/// Name of the SPARSE_FLOAT_VECTOR field (`sparse`) generated by BM25 function.
const FIELD_SPARSE: &str = "sparse";
/// Name of the FLOAT_VECTOR field (`embedding`).
const FIELD_EMBEDDING: &str = "embedding";
/// Name of the per-row fingerprint field (`fp`).
const FIELD_FP: &str = "fp";
/// Name of the content hash field (`hash`).
const FIELD_HASH: &str = "hash";
/// Name of the source provenance field (`source`).
const FIELD_SOURCE: &str = "source";
/// Name of the source file path field (`path`).
const FIELD_PATH: &str = "path";
/// Name of the creation timestamp field (`created_at`).
const FIELD_CREATED_AT: &str = "created_at";

/// Max characters for the VARCHAR id field. Memory chunk ids and prime
/// opaque item ids are bounded ASCII well below this.
const ID_MAX_CHARS: u32 = 512;
/// Max characters for the VARCHAR text field (analyzed chunks).
const TEXT_MAX_CHARS: u32 = 65535;
/// Max characters for the fingerprint field (short hex digest).
const FP_MAX_CHARS: u32 = 128;
/// Max characters for the blake3 content hash field.
const HASH_MAX_CHARS: u32 = 64;
/// Max characters for the source field.
const SOURCE_MAX_CHARS: u32 = 64;
/// Max characters for the file path field.
const PATH_MAX_CHARS: u32 = 512;

/// Milvus-backed [`VectorMirror`] (feature `milvus`).
pub struct MilvusStore {
    client: ClientV2,
    /// Bearer token, held only for error-detail redaction. Never logged or
    /// rendered by [`Debug`]; never persisted anywhere.
    token: Option<String>,
    timeout: Duration,
}

impl std::fmt::Debug for MilvusStore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Secret-free by construction: never render client internals.
        f.debug_struct("MilvusStore")
            .field("backend", &"milvus")
            .field("timeout_secs", &self.timeout.as_secs())
            .finish()
    }
}

impl MilvusStore {
    /// Connect to a Milvus standalone/server (`uri` like
    /// `http://localhost:19530`; optional bearer token).
    ///
    /// The token never appears in the returned error detail unredacted.
    pub async fn connect(
        uri: &str,
        token: Option<&str>,
        timeout: Duration,
    ) -> Result<Self, MirrorError> {
        if uri.trim().is_empty() {
            return Err(MirrorError::new(MirrorErrorKind::Malformed));
        }
        let mut config = ConnectConfig::new().uri(uri.trim().to_owned());
        if let Some(token) = token.filter(|t| !t.is_empty()) {
            config = config.token(token.to_owned());
        }
        // The SDK default retries idempotent RPCs 75 times with a 3 s
        // backoff cap and NO total wall-clock bound (`max_retry_timeout`
        // defaults to zero). During an outage that lets one logical call
        // retry far past the mirror budget (a live kill test measured
        // ~211 s), so cap the whole retry policy at the configured timeout:
        // brief blips still get fast retries, real outages fail bounded.
        config = config.retry(
            RetryConfig::new()
                .max_retry_timeout(timeout)
                .max_backoff(Duration::from_millis(500)),
        );
        let client = ClientV2::new(&config)
            .await
            .map_err(|e| mirror_error(&e, token))?;
        // Per-RPC deadline mirrors the consumer-side tokio timeouts: no
        // single call can hang past the configured budget.
        client.set_rpc_deadline(timeout);
        Ok(Self {
            client,
            token: token.map(str::to_owned),
            timeout,
        })
    }

    fn error(&self, kind: MirrorErrorKind, source: &Error) -> MirrorError {
        MirrorError::with_detail(kind, source.to_string(), self.token.as_deref())
    }

    fn transient(&self, source: &Error) -> MirrorError {
        self.error(MirrorErrorKind::Transient, source)
    }

    /// Ensure the collection exists with the expected tag; drop + recreate
    /// on absent/mismatched tag or a dimension change.
    async fn ensure_collection_inner(
        &self,
        name: &str,
        dims: u32,
        fingerprint_hash: &str,
    ) -> Result<(), Error> {
        let exists = self
            .client
            .has_collection(
                HasCollectionRequest::builder()
                    .collection_name(name)
                    .build()?,
            )
            .await?
            .exists();
        if exists {
            let description = self
                .client
                .describe_collection(
                    DescribeCollectionRequest::builder()
                        .collection_name(name)
                        .build()?,
                )
                .await?
                .description()
                .get_description()
                .to_owned();
            let compatible = matches!(
                parse_collection_tag(&description),
                Some((ref tag_hash, tag_dims, tag_schema_version))
                if tag_hash == fingerprint_hash
                    && tag_dims == dims
                    && tag_schema_version == crate::fingerprint::VECTOR_SCHEMA_VERSION
            );
            if compatible {
                // Keep the loaded state fresh; loading an already loaded
                // collection is a server-side no-op.
                self.client
                    .load_collection(
                        LoadCollectionRequest::builder()
                            .collection_name(name)
                            .sync(false)
                            .build()?,
                    )
                    .await?;
                return Ok(());
            }
            // Incompatible or untagged: destroy and rebuild from SQLite.
            self.client
                .drop_collection(
                    DropCollectionRequest::builder()
                        .collection_name(name)
                        .build()?,
                )
                .await?;
        }
        let schema = CollectionSchema::new()
            .add_field(
                FieldSchema::new()
                    .name(FIELD_ID)
                    .data_type(DataType::VarChar)
                    .primary_key(true)
                    .max_length(ID_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_EMBEDDING)
                    .data_type(DataType::FloatVector)
                    .dimension(dims),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_FP)
                    .data_type(DataType::VarChar)
                    .max_length(FP_MAX_CHARS),
            );
        let tag = collection_tag(
            fingerprint_hash,
            dims,
            crate::fingerprint::VECTOR_SCHEMA_VERSION,
        );
        self.client
            .create_collection(
                CreateCollectionRequest::builder()
                    .collection_name(name)
                    .description(tag)
                    .schema(schema)
                    .index_param(
                        IndexParam::new()
                            .field_name(FIELD_EMBEDDING)
                            .index_type(IndexType::AutoIndex)
                            .metric_type(MetricType::Ip),
                    )
                    .build()?,
            )
            .await?;
        // create_collection starts loading asynchronously when index params
        // are present; this accepted-load request is an idempotent backstop.
        self.client
            .load_collection(
                LoadCollectionRequest::builder()
                    .collection_name(name)
                    .sync(false)
                    .build()?,
            )
            .await?;
        Ok(())
    }

    /// Build one schema-shaped row for the row-based upsert path.
    fn upsert_row(&self, id: &str, vector: &[f32], fingerprint_hash: &str) -> serde_json::Value {
        let mut row = serde_json::Map::with_capacity(3);
        row.insert(FIELD_ID.to_owned(), serde_json::json!(id));
        row.insert(FIELD_EMBEDDING.to_owned(), serde_json::json!(vector));
        row.insert(FIELD_FP.to_owned(), serde_json::json!(fingerprint_hash));
        serde_json::Value::Object(row)
    }

    /// Ensure the schema-v2 collection exists with the expected tag (version 2);
    /// drop + recreate on absent/mismatched tag, dimension change, or v1 tag.
    async fn ensure_collection_v2_inner(
        &self,
        name: &str,
        dims: u32,
        fingerprint_hash: &str,
    ) -> Result<(), Error> {
        let exists = self
            .client
            .has_collection(
                HasCollectionRequest::builder()
                    .collection_name(name)
                    .build()?,
            )
            .await?
            .exists();
        if exists {
            let description = self
                .client
                .describe_collection(
                    DescribeCollectionRequest::builder()
                        .collection_name(name)
                        .build()?,
                )
                .await?
                .description()
                .get_description()
                .to_owned();
            let compatible = matches!(
                parse_collection_tag(&description),
                Some((ref tag_hash, tag_dims, tag_schema_version))
                if tag_hash == fingerprint_hash
                    && tag_dims == dims
                    && tag_schema_version == MEMORY_SCHEMA_VERSION_V2
            );
            if compatible {
                self.client
                    .load_collection(
                        LoadCollectionRequest::builder()
                            .collection_name(name)
                            .sync(false)
                            .build()?,
                    )
                    .await?;
                return Ok(());
            }
            self.client
                .drop_collection(
                    DropCollectionRequest::builder()
                        .collection_name(name)
                        .build()?,
                )
                .await?;
        }
        let schema = CollectionSchema::new()
            .add_field(
                FieldSchema::new()
                    .name(FIELD_ID)
                    .data_type(DataType::VarChar)
                    .primary_key(true)
                    .max_length(ID_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_TEXT)
                    .data_type(DataType::VarChar)
                    .max_length(TEXT_MAX_CHARS)
                    .enable_analyzer(true)
                    .enable_match(true),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_SPARSE)
                    .data_type(DataType::SparseFloatVector),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_EMBEDDING)
                    .data_type(DataType::FloatVector)
                    .dimension(dims),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_FP)
                    .data_type(DataType::VarChar)
                    .max_length(FP_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_HASH)
                    .data_type(DataType::VarChar)
                    .max_length(HASH_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_SOURCE)
                    .data_type(DataType::VarChar)
                    .max_length(SOURCE_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_PATH)
                    .data_type(DataType::VarChar)
                    .max_length(PATH_MAX_CHARS),
            )
            .add_field(
                FieldSchema::new()
                    .name(FIELD_CREATED_AT)
                    .data_type(DataType::Int64),
            )
            .add_function(
                Function::new()
                    .name("bm25_fn")
                    .description("BM25 text to sparse")
                    .function_type(FunctionType::Bm25)
                    .input_fields([FIELD_TEXT])
                    .output_fields([FIELD_SPARSE]),
            );
        let tag = collection_tag(
            fingerprint_hash,
            dims,
            MEMORY_SCHEMA_VERSION_V2,
        );
        self.client
            .create_collection(
                CreateCollectionRequest::builder()
                    .collection_name(name)
                    .description(tag)
                    .schema(schema)
                    .index_param(
                        IndexParam::new()
                            .field_name(FIELD_EMBEDDING)
                            .index_type(IndexType::AutoIndex)
                            .metric_type(MetricType::Ip),
                    )
                    .index_param(
                        IndexParam::new()
                            .field_name(FIELD_SPARSE)
                            .index_type(IndexType::AutoIndex)
                            .metric_type(MetricType::Bm25),
                    )
                    .build()?,
            )
            .await?;
        self.client
            .load_collection(
                LoadCollectionRequest::builder()
                    .collection_name(name)
                    .sync(false)
                    .build()?,
            )
            .await?;
        Ok(())
    }

    /// Build one schema-v2 shaped row for the row-based upsert path.
    fn upsert_row_v2(&self, row: &MemoryRow) -> serde_json::Value {
        let mut obj = serde_json::Map::with_capacity(8);
        obj.insert(FIELD_ID.to_owned(), serde_json::json!(row.id));
        obj.insert(FIELD_TEXT.to_owned(), serde_json::json!(row.text));
        obj.insert(FIELD_EMBEDDING.to_owned(), serde_json::json!(row.vector));
        obj.insert(FIELD_FP.to_owned(), serde_json::json!(row.fingerprint_hash));
        obj.insert(FIELD_HASH.to_owned(), serde_json::json!(row.hash));
        obj.insert(FIELD_SOURCE.to_owned(), serde_json::json!(row.source));
        obj.insert(FIELD_PATH.to_owned(), serde_json::json!(row.path));
        obj.insert(FIELD_CREATED_AT.to_owned(), serde_json::json!(row.created_at));
        serde_json::Value::Object(obj)
    }
}

#[async_trait]
impl VectorMirror for MilvusStore {
    fn backend_id(&self) -> &str {
        "milvus"
    }

    async fn ensure_collection(
        &self,
        name: &str,
        dims: u32,
        fingerprint_hash: &str,
    ) -> Result<(), MirrorError> {
        self.ensure_collection_inner(name, dims, fingerprint_hash)
            .await
            .map_err(|e| self.transient(&e))
    }

    async fn upsert(
        &self,
        name: &str,
        ids: &[String],
        vectors: &[Vec<f32>],
        fingerprint_hash: &str,
    ) -> Result<(), MirrorError> {
        if ids.len() != vectors.len() {
            return Err(MirrorError::new(MirrorErrorKind::Malformed));
        }
        // Row-based input: `id`/`embedding`/`fp` match the collection
        // schema; VARCHAR primary keys make the upsert idempotent.
        let rows: Vec<serde_json::Value> = ids
            .iter()
            .zip(vectors.iter())
            .map(|(id, vector)| self.upsert_row(id, vector, fingerprint_hash))
            .collect();
        let insert = InsertRequest::builder()
            .collection_name(name)
            .rows(rows)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let request = UpsertRequest::builder()
            .insert(insert)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        self.client
            .upsert(request)
            .await
            .map_err(|e| self.transient(&e))?;
        Ok(())
    }

    async fn delete(&self, name: &str, ids: &[String]) -> Result<(), MirrorError> {
        if ids.is_empty() {
            return Ok(());
        }
        let request = DeleteRequest::builder()
            .collection_name(name)
            .ids(Ids::VarChar(ids.to_vec()))
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        self.client
            .delete(request)
            .await
            .map_err(|e| self.transient(&e))?;
        Ok(())
    }

    async fn knn(
        &self,
        name: &str,
        query: &[f32],
        k: usize,
        fingerprint_hash: &str,
    ) -> Result<Vec<(String, f32)>, MirrorError> {
        let request = SearchRequest::builder()
            .collection_name(name)
            .vector_field(FIELD_EMBEDDING)
            .vectors(SearchVectors::Float(vec![query.to_vec()]))
            // Single-fingerprint collection; the per-row filter is defense
            // in depth while a recreated collection repopulates.
            .filter(format!("{FIELD_FP} == \"{}\"", fingerprint_hash))
            .output_fields([FIELD_ID])
            .limit(k.max(1) as i64)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let response = self
            .client
            .search(request)
            .await
            .map_err(|e| self.transient(&e))?;
        let mut hits = Vec::new();
        for single in response.results().iter() {
            let Ids::VarChar(hit_ids) = single.get_ids() else {
                return Err(MirrorError::new(MirrorErrorKind::Malformed));
            };
            let scores = single.get_scores();
            for (id, score) in hit_ids.iter().zip(scores.iter()) {
                hits.push((id.clone(), similarity_to_l2_distance(*score)));
            }
        }
        hits.truncate(k.max(1));
        Ok(hits)
    }

    async fn count(&self, name: &str, _fingerprint_hash: &str) -> Result<u64, MirrorError> {
        // A mirrored collection is single-fingerprint (the tag gate drops +
        // recreates on mismatch), so the collection-wide row count is the
        // fingerprint-filtered count. Counted via the `count(*)` query
        // aggregate over the loaded collection: collection stats
        // (`row_count`) only cover flushed segments, so freshly upserted
        // rows — searchable in the growing segment — read as 0 until Milvus
        // flushes on its own cadence. The readiness gate must reflect the
        // SERVABLE set, not the persisted set.
        let request = QueryRequest::builder()
            .collection_name(name)
            .filter("")
            .output_fields(vec!["count(*)".to_owned()])
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let response = self
            .client
            .query(request)
            .await
            .map_err(|e| self.transient(&e))?;
        let aggregate = response
            .results()
            .get_output_field("count(*)")
            .ok_or_else(|| {
                MirrorError::with_detail(
                    MirrorErrorKind::Malformed,
                    "count(*) column missing in query result".to_owned(),
                    None,
                )
            })?;
        let parsed = match aggregate {
            FieldData::Int64 { values, .. } => values.first().copied(),
            FieldData::Int32 { values, .. } => values.first().copied().map(i64::from),
            FieldData::Int16 { values, .. } => values.first().copied().map(i64::from),
            FieldData::Int8 { values, .. } => values.first().copied().map(i64::from),
            _ => None,
        };
        parsed.map(|v| v.max(0) as u64).ok_or_else(|| {
            MirrorError::with_detail(
                MirrorErrorKind::Malformed,
                "count(*) aggregate returned no value".to_owned(),
                None,
            )
        })
    }

    async fn drop_collection(&self, name: &str) -> Result<(), MirrorError> {
        let request = DropCollectionRequest::builder()
            .collection_name(name)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        self.client
            .drop_collection(request)
            .await
            .map_err(|e| self.transient(&e))
    }

    async fn ensure_collection_v2(
        &self,
        name: &str,
        dims: u32,
        fingerprint_hash: &str,
    ) -> Result<(), MirrorError> {
        self.ensure_collection_v2_inner(name, dims, fingerprint_hash)
            .await
            .map_err(|e| self.transient(&e))
    }

    async fn upsert_rows_v2(
        &self,
        name: &str,
        rows: &[MemoryRow],
    ) -> Result<(), MirrorError> {
        if rows.is_empty() {
            return Ok(());
        }
        let json_rows: Vec<serde_json::Value> = rows
            .iter()
            .map(|r| self.upsert_row_v2(r))
            .collect();
        let insert = InsertRequest::builder()
            .collection_name(name)
            .rows(json_rows)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let request = UpsertRequest::builder()
            .insert(insert)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        self.client
            .upsert(request)
            .await
            .map_err(|e| self.transient(&e))?;
        Ok(())
    }

    async fn bm25_search_v2(
        &self,
        name: &str,
        query: &str,
        k: usize,
        fingerprint_hash: &str,
    ) -> Result<Vec<RemoteSearchHit>, MirrorError> {
        let request = SearchRequest::builder()
            .collection_name(name)
            .vector_field(FIELD_SPARSE)
            .vectors(SearchVectors::EmbeddedText(vec![query.to_owned()]))
            .filter(format!("{FIELD_FP} == \"{}\"", fingerprint_hash))
            .output_fields([FIELD_ID, FIELD_TEXT, FIELD_PATH, FIELD_SOURCE, FIELD_CREATED_AT])
            .limit(k.max(1) as i64)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let response = self
            .client
            .search(request)
            .await
            .map_err(|e| self.transient(&e))?;
        parse_search_hits(response.results(), k, false)
    }

    async fn knn_v2(
        &self,
        name: &str,
        query: &[f32],
        k: usize,
        fingerprint_hash: &str,
    ) -> Result<Vec<RemoteSearchHit>, MirrorError> {
        let request = SearchRequest::builder()
            .collection_name(name)
            .vector_field(FIELD_EMBEDDING)
            .vectors(SearchVectors::Float(vec![query.to_vec()]))
            .filter(format!("{FIELD_FP} == \"{}\"", fingerprint_hash))
            .output_fields([FIELD_ID, FIELD_TEXT, FIELD_PATH, FIELD_SOURCE, FIELD_CREATED_AT])
            .limit(k.max(1) as i64)
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let response = self
            .client
            .search(request)
            .await
            .map_err(|e| self.transient(&e))?;
        parse_search_hits(response.results(), k, true)
    }

    async fn list_id_hashes_v2(
        &self,
        name: &str,
        fingerprint_hash: &str,
    ) -> Result<std::collections::HashMap<String, String>, MirrorError> {
        let request = QueryRequest::builder()
            .collection_name(name)
            .filter(format!("{FIELD_FP} == \"{}\"", fingerprint_hash))
            .output_fields(vec![FIELD_ID.to_owned(), FIELD_HASH.to_owned()])
            .build()
            .map_err(|e| self.error(MirrorErrorKind::Malformed, &e))?;
        let response = self
            .client
            .query(request)
            .await
            .map_err(|e| self.transient(&e))?;

        let ids_data = response.results().get_output_field(FIELD_ID);
        let hashes_data = response.results().get_output_field(FIELD_HASH);

        let ids = extract_varchar_slice(ids_data);
        let hashes = extract_varchar_slice(hashes_data);

        let mut map = std::collections::HashMap::new();
        if let (Some(ids), Some(hashes)) = (ids, hashes) {
            for (id, hash) in ids.iter().zip(hashes.iter()) {
                map.insert(id.clone(), hash.clone());
            }
        }
        Ok(map)
    }
}

fn parse_search_hits(
    results: &milvus::v2::response::dql::SearchResults,
    k: usize,
    is_dense_knn: bool,
) -> Result<Vec<RemoteSearchHit>, MirrorError> {
    let mut hits = Vec::new();
    for single in results.iter() {
        let Ids::VarChar(ids) = single.get_ids() else {
            return Err(MirrorError::new(MirrorErrorKind::Malformed));
        };
        let scores = single.get_scores();
        let texts = extract_varchar_slice(single.get_output_field(FIELD_TEXT));
        let paths = extract_varchar_slice(single.get_output_field(FIELD_PATH));
        let sources = extract_varchar_slice(single.get_output_field(FIELD_SOURCE));
        let created_ats = extract_int64_slice(single.get_output_field(FIELD_CREATED_AT));

        for (i, id) in ids.iter().enumerate() {
            let raw_score = scores.get(i).copied().unwrap_or(0.0);
            let score = if is_dense_knn {
                similarity_to_l2_distance(raw_score)
            } else {
                raw_score
            };
            let text = texts.and_then(|v| v.get(i)).cloned().unwrap_or_default();
            let path = paths.and_then(|v| v.get(i)).cloned().unwrap_or_default();
            let source = sources.and_then(|v| v.get(i)).cloned().unwrap_or_default();
            let created_at = created_ats.and_then(|v| v.get(i)).copied().unwrap_or(0);

            hits.push(RemoteSearchHit {
                id: id.clone(),
                score,
                text,
                path,
                source,
                created_at,
            });
        }
    }
    hits.truncate(k.max(1));
    Ok(hits)
}

fn extract_varchar_slice(field: Option<&FieldData>) -> Option<&[String]> {
    match field {
        Some(FieldData::VarChar { values, .. }) => Some(values.as_slice()),
        _ => None,
    }
}

fn extract_int64_slice(field: Option<&FieldData>) -> Option<&[i64]> {
    match field {
        Some(FieldData::Int64 { values, .. }) => Some(values.as_slice()),
        _ => None,
    }
}

/// Map an SDK error to a mirror failure kind without leaking the token.
///
/// Server bodies can embed request payloads; the detail passes through
/// [`MirrorError::with_detail`], which redacts the bearer token, strips
/// control characters, and truncates.
fn mirror_error(source: &Error, token: Option<&str>) -> MirrorError {
    let kind = match source {
        Error::Grpc(_) => MirrorErrorKind::Transient,
        Error::Server(_) => MirrorErrorKind::SourceUnavailable,
        Error::Conversion(_) | Error::Validation(_) | Error::MalformedResponse(_) => {
            MirrorErrorKind::Malformed
        }
        Error::Timeout(_) => MirrorErrorKind::BudgetExhausted,
        Error::Cancelled(_) => MirrorErrorKind::Cancelled,
        Error::RetryExhausted { .. } | Error::BulkImport(_) | Error::Unexpected(_) => {
            MirrorErrorKind::Transient
        }
        _ => MirrorErrorKind::Transient,
    };
    MirrorError::with_detail(kind, source.to_string(), token)
}

/// Convenience constructor used by the shell-side resolver: builds an
/// `Arc`-wrapped store ready to be upcast into a [`MirrorHandle`].
pub async fn connect_store(
    uri: &str,
    token: Option<&str>,
    timeout: Duration,
) -> Result<Arc<MilvusStore>, MirrorError> {
    MilvusStore::connect(uri, token, timeout)
        .await
        .map(Arc::new)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sdk_errors_map_to_mirror_kinds_without_token_leaks() {
        let token = "secret-token";
        let timeout = Error::Timeout("rpc deadline exceeded".to_owned());
        assert_eq!(
            mirror_error(&timeout, Some(token)).kind(),
            MirrorErrorKind::BudgetExhausted
        );
        let malformed = Error::MalformedResponse("no result for search".to_owned());
        assert_eq!(
            mirror_error(&malformed, Some(token)).kind(),
            MirrorErrorKind::Malformed
        );
        let cancelled = Error::Cancelled("call dropped".to_owned());
        assert_eq!(
            mirror_error(&cancelled, Some(token)).kind(),
            MirrorErrorKind::Cancelled
        );
        let unexpected = Error::Unexpected("invariant violated: token=secret-token".to_owned());
        let err = mirror_error(&unexpected, Some(token));
        assert_eq!(err.kind(), MirrorErrorKind::Transient);
        assert!(!err.detail().contains("secret-token"), "{}", err.detail());
    }

    #[test]
    fn uri_validation_rejects_empty() {
        let result = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(MilvusStore::connect("   ", None, Duration::from_secs(1)));
        assert_eq!(result.unwrap_err().kind(), MirrorErrorKind::Malformed);
    }
}

// ---------------------------------------------------------------------------
// Live Milvus conformance (plan Phase 4, item 14)
// ---------------------------------------------------------------------------

/// Live Milvus conformance suite for [`MilvusStore`].
///
/// `#[ignore]`-gated: the tests compile everywhere but execute only against
/// a real Milvus standalone/server:
///
/// ```text
/// GROK_MILVUS_TEST_URI=http://localhost:19530 \
/// GROK_MILVUS_TEST_TOKEN=... \
/// ./grok-test.sh -p xai-grok-memory --run-ignored all
/// ```
///
/// Both variables are required; when either is unset every test returns
/// early, so an `--run-ignored all` run without a server stays green (a
/// clean skip, following the `conformance/zai.rs` precedent). An empty
/// token value selects an unauthenticated standalone instance. Each test
/// allocates a uniquely named `grok_mem_livetest_*` collection and drops
/// it once its assertions finish; a panicked run may leave that uniquely
/// named collection behind on the server.
#[cfg(test)]
mod live_conformance {
    use super::*;
    use crate::mirror::mirror_timeout;

    /// Orthonormal unit fixtures: Milvus `IP` over unit vectors returns the
    /// cosine similarity, so fixture-vs-fixture similarity is exactly 1.0
    /// (identical) or 0.0 (orthogonal).
    const VEC_A: [f32; 4] = [1.0, 0.0, 0.0, 0.0];
    const VEC_B: [f32; 4] = [0.0, 1.0, 0.0, 0.0];
    const VEC_C: [f32; 4] = [0.0, 0.0, 1.0, 0.0];

    /// Schema dimensionality for the live collections (matches the
    /// fixtures).
    const DIMS: u32 = VEC_A.len() as u32;

    /// Distinct lowercase-hex fingerprint hashes. Opaque short digests to
    /// the store; the two values drive the recreation test's tag mismatch.
    const FP_A: &str = "0123456789abcdef";
    const FP_B: &str = "fedcba9876543210";

    const ID_A: &str = "livetest-vec-a";
    const ID_B: &str = "livetest-vec-b";
    const ID_C: &str = "livetest-vec-c";

    /// f32 tolerance for converted distances: `IP` on one-hot unit vectors
    /// is exact in fp32, but a small epsilon keeps the assertions robust to
    /// server-side summation order across AUTOINDEX implementations.
    const DISTANCE_EPSILON: f32 = 1e-3;

    /// Bounded polling budget for eventually consistent visibility (same
    /// pattern as the resync engine's count verification, sized for a live
    /// server).
    const LIVE_POLLS: u32 = 30;
    const LIVE_POLL_BACKOFF: Duration = Duration::from_millis(500);

    /// Read the live-suite gate: both `GROK_MILVUS_TEST_URI` and
    /// `GROK_MILVUS_TEST_TOKEN` must be set. `None` means skip cleanly.
    fn live_config() -> Option<(String, Option<String>)> {
        let uri = std::env::var("GROK_MILVUS_TEST_URI").ok()?;
        if uri.trim().is_empty() {
            return None;
        }
        let token = std::env::var("GROK_MILVUS_TEST_TOKEN").ok()?;
        // An empty token value selects an unauthenticated instance.
        Some((uri, (!token.is_empty()).then_some(token)))
    }

    /// Connect to the live instance with the crate's default mirror
    /// timeout.
    async fn connect_live(uri: &str, token: Option<&str>) -> MilvusStore {
        MilvusStore::connect(uri, token, mirror_timeout(None))
            .await
            .expect("connect to the live Milvus instance")
    }

    /// Uniquely named collection per test process and run
    /// (`grok_mem_livetest_<slug>_<pid>_<millis>`), so repeated or
    /// concurrent runs never collide with each other or with real
    /// workspace collections.
    fn live_collection_name(slug: &str) -> String {
        let pid = std::process::id();
        let millis = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|elapsed| elapsed.as_millis())
            .unwrap_or_default();
        format!("grok_mem_livetest_{slug}_{pid}_{millis}")
    }

    /// Poll `count` until it reports `expected`: Milvus row-count stats are
    /// eventually consistent, so verification uses bounded retries exactly
    /// like the resync engine. Panics with a secret-free diagnostic when
    /// the budget is exhausted.
    async fn wait_for_count(
        store: &MilvusStore,
        name: &str,
        fingerprint: &str,
        expected: u64,
    ) -> u64 {
        let mut last_count: u64 = 0;
        let mut last_error: Option<MirrorError> = None;
        for attempt in 0..LIVE_POLLS {
            match store.count(name, fingerprint).await {
                Ok(count) if count == expected => return count,
                Ok(count) => {
                    last_count = count;
                    last_error = None;
                }
                Err(error) => last_error = Some(error),
            }
            if attempt + 1 < LIVE_POLLS {
                tokio::time::sleep(LIVE_POLL_BACKOFF).await;
            }
        }
        if let Some(error) = last_error {
            panic!("count never reached {expected} within {LIVE_POLLS} polls: {error:?}");
        }
        panic!("count never reached {expected} within {LIVE_POLLS} polls (last: {last_count})");
    }

    /// Poll `knn` until `predicate` holds: upsert visibility in Milvus is
    /// eventually consistent. Panics when the budget is exhausted.
    async fn wait_for_knn(
        store: &MilvusStore,
        name: &str,
        query: &[f32],
        k: usize,
        fingerprint: &str,
        what: &str,
        predicate: impl Fn(&[(String, f32)]) -> bool,
    ) -> Vec<(String, f32)> {
        let mut last_hits: Vec<(String, f32)> = Vec::new();
        for attempt in 0..LIVE_POLLS {
            match store.knn(name, query, k, fingerprint).await {
                Ok(hits) => {
                    if predicate(&hits) {
                        return hits;
                    }
                    last_hits = hits;
                }
                Err(error) if attempt + 1 == LIVE_POLLS => {
                    panic!("knn never succeeded ({what}) within {LIVE_POLLS} polls: {error:?}")
                }
                Err(_) => {}
            }
            if attempt + 1 < LIVE_POLLS {
                tokio::time::sleep(LIVE_POLL_BACKOFF).await;
            }
        }
        panic!("knn never satisfied ({what}) within {LIVE_POLLS} polls; last hits: {last_hits:?}");
    }

    /// (1) `ensure_collection` + `upsert` + `count` round-trip: a fresh
    /// collection starts empty, accepts three rows, and reports them back
    /// through the row-count stats.
    #[tokio::test]
    #[ignore = "live Milvus conformance; requires GROK_MILVUS_TEST_URI and GROK_MILVUS_TEST_TOKEN"]
    async fn live_ensure_collection_upsert_and_count_round_trip() {
        let Some((uri, token)) = live_config() else {
            // Clean skip: both variables are required for the live suite.
            return;
        };
        let store = connect_live(&uri, token.as_deref()).await;
        let name = live_collection_name("roundtrip");

        store
            .ensure_collection(&name, DIMS, FP_A)
            .await
            .expect("ensure_collection creates the live collection");
        wait_for_count(&store, &name, FP_A, 0).await;

        let ids = vec![ID_A.to_owned(), ID_B.to_owned(), ID_C.to_owned()];
        let vectors = vec![VEC_A.to_vec(), VEC_B.to_vec(), VEC_C.to_vec()];
        store
            .upsert(&name, &ids, &vectors, FP_A)
            .await
            .expect("upsert three rows into the live collection");

        wait_for_count(&store, &name, FP_A, 3).await;

        store
            .drop_collection(&name)
            .await
            .expect("drop the live test collection");
    }

    /// (2) KNN returns the expected nearest id, with distances converted
    /// from the server's `IP` similarity by the seam's score contract
    /// `√(2·(1 − sim))`: sim 1.0 (identical unit vectors) → 0.0, sim 0.0
    /// (orthogonal) → √2.
    #[tokio::test]
    #[ignore = "live Milvus conformance; requires GROK_MILVUS_TEST_URI and GROK_MILVUS_TEST_TOKEN"]
    async fn live_knn_returns_expected_nearest_id_with_l2_distance_conversion() {
        let Some((uri, token)) = live_config() else {
            return;
        };
        let store = connect_live(&uri, token.as_deref()).await;
        let name = live_collection_name("knn");

        store
            .ensure_collection(&name, DIMS, FP_A)
            .await
            .expect("ensure_collection creates the live collection");
        let ids = vec![ID_A.to_owned(), ID_B.to_owned(), ID_C.to_owned()];
        let vectors = vec![VEC_A.to_vec(), VEC_B.to_vec(), VEC_C.to_vec()];
        store
            .upsert(&name, &ids, &vectors, FP_A)
            .await
            .expect("upsert three rows into the live collection");

        // The query equals VEC_A exactly, so VEC_A must rank first with a
        // converted distance of 0.0, and either orthogonal fixture must
        // rank second with √2.
        let expected_nearest = similarity_to_l2_distance(1.0);
        let expected_orthogonal = similarity_to_l2_distance(0.0);
        let hits = wait_for_knn(
            &store,
            &name,
            &VEC_A,
            2,
            FP_A,
            "the nearest id and one runner-up are visible",
            |hits: &[(String, f32)]| hits.len() == 2 && hits[0].0 == ID_A,
        )
        .await;

        let nearest_id = &hits[0].0;
        let nearest_distance = hits[0].1;
        assert_eq!(nearest_id, ID_A);
        assert!(
            (nearest_distance - expected_nearest).abs() < DISTANCE_EPSILON,
            "nearest distance {nearest_distance} must convert similarity 1.0 to {expected_nearest}"
        );
        let runner_up_id = &hits[1].0;
        let runner_up_distance = hits[1].1;
        assert_ne!(runner_up_id, ID_A);
        assert!(
            (runner_up_distance - expected_orthogonal).abs() < DISTANCE_EPSILON,
            "orthogonal distance {runner_up_distance} must convert similarity 0.0 \
             to {expected_orthogonal}"
        );

        store
            .drop_collection(&name)
            .await
            .expect("drop the live test collection");
    }

    /// (3) `delete` removes the targeted id: the row count drops and the
    /// deleted id stops appearing in KNN results while the surviving row
    /// remains.
    #[tokio::test]
    #[ignore = "live Milvus conformance; requires GROK_MILVUS_TEST_URI and GROK_MILVUS_TEST_TOKEN"]
    async fn live_delete_removes_the_id() {
        let Some((uri, token)) = live_config() else {
            return;
        };
        let store = connect_live(&uri, token.as_deref()).await;
        let name = live_collection_name("delete");

        store
            .ensure_collection(&name, DIMS, FP_A)
            .await
            .expect("ensure_collection creates the live collection");
        let ids = vec![ID_A.to_owned(), ID_B.to_owned()];
        let vectors = vec![VEC_A.to_vec(), VEC_B.to_vec()];
        store
            .upsert(&name, &ids, &vectors, FP_A)
            .await
            .expect("upsert two rows into the live collection");
        wait_for_count(&store, &name, FP_A, 2).await;

        // Sanity: both rows are visible to KNN before the delete.
        wait_for_knn(
            &store,
            &name,
            &VEC_A,
            2,
            FP_A,
            "both rows are visible",
            |hits: &[(String, f32)]| {
                hits.len() == 2
                    && hits.iter().any(|(id, _)| id == ID_A)
                    && hits.iter().any(|(id, _)| id == ID_B)
            },
        )
        .await;

        store
            .delete(&name, &[ID_A.to_owned()])
            .await
            .expect("delete the targeted id");
        wait_for_count(&store, &name, FP_A, 1).await;

        let hits = wait_for_knn(
            &store,
            &name,
            &VEC_A,
            2,
            FP_A,
            "the deleted id is gone",
            |hits: &[(String, f32)]| {
                !hits.iter().any(|(id, _)| id == ID_A) && hits.iter().any(|(id, _)| id == ID_B)
            },
        )
        .await;
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].0, ID_B);

        store
            .drop_collection(&name)
            .await
            .expect("drop the live test collection");
    }

    /// (4) A fingerprint mismatch forces collection recreation: re-ensuring
    /// the same collection under a different fingerprint empties it, and
    /// the recreated collection is immediately usable under the new tag.
    #[tokio::test]
    #[ignore = "live Milvus conformance; requires GROK_MILVUS_TEST_URI and GROK_MILVUS_TEST_TOKEN"]
    async fn live_fingerprint_mismatch_forces_collection_recreation() {
        let Some((uri, token)) = live_config() else {
            return;
        };
        let store = connect_live(&uri, token.as_deref()).await;
        let name = live_collection_name("recreate");

        // Populate the collection under fingerprint A.
        store
            .ensure_collection(&name, DIMS, FP_A)
            .await
            .expect("ensure_collection creates the live collection");
        let ids = vec![ID_A.to_owned(), ID_B.to_owned()];
        let vectors = vec![VEC_A.to_vec(), VEC_B.to_vec()];
        store
            .upsert(&name, &ids, &vectors, FP_A)
            .await
            .expect("upsert two rows under fingerprint A");
        wait_for_count(&store, &name, FP_A, 2).await;

        // The mismatched tag must drop + recreate the collection, leaving
        // it empty.
        store
            .ensure_collection(&name, DIMS, FP_B)
            .await
            .expect("ensure_collection recreates on fingerprint mismatch");
        wait_for_count(&store, &name, FP_B, 0).await;

        // The recreated collection is immediately usable under the new tag.
        store
            .upsert(&name, &[ID_C.to_owned()], &[VEC_C.to_vec()], FP_B)
            .await
            .expect("upsert into the recreated collection");
        wait_for_count(&store, &name, FP_B, 1).await;

        store
            .drop_collection(&name)
            .await
            .expect("drop the live test collection");
    }

    /// (5) Live test for Schema-v2 + BM25 function on Milvus server (verifies 2.5.16 vs 2.6.0 SDK).
    #[tokio::test]
    #[ignore = "live Milvus conformance; requires GROK_MILVUS_TEST_URI and GROK_MILVUS_TEST_TOKEN"]
    async fn live_schema_v2_bm25_spike() {
        let Some((uri, token)) = live_config() else {
            return;
        };
        let store = connect_live(&uri, token.as_deref()).await;
        let name = live_collection_name("bm25_v2");

        store
            .ensure_collection_v2(&name, DIMS, FP_A)
            .await
            .expect("ensure_collection_v2 creates the live collection with BM25 function");

        let row1 = MemoryRow {
            id: "row1".to_string(),
            text: "Rust systems programming and memory safety".to_string(),
            vector: VEC_A.to_vec(),
            fingerprint_hash: FP_A.to_string(),
            hash: "hash_row1_blake3".to_string(),
            source: "user".to_string(),
            path: "memory/notes.md".to_string(),
            created_at: 1700000000,
        };
        let row2 = MemoryRow {
            id: "row2".to_string(),
            text: "Python async programming and event loops".to_string(),
            vector: VEC_B.to_vec(),
            fingerprint_hash: FP_A.to_string(),
            hash: "hash_row2_blake3".to_string(),
            source: "user".to_string(),
            path: "memory/python.md".to_string(),
            created_at: 1700000001,
        };

        store
            .upsert_rows_v2(&name, &[row1.clone(), row2.clone()])
            .await
            .expect("upsert_rows_v2 adds schema-v2 rows");

        // BM25 full-text keyword search
        let bm25_hits = store
            .bm25_search_v2(&name, "Rust memory safety", 5, FP_A)
            .await
            .expect("bm25_search_v2 runs search");
        assert!(!bm25_hits.is_empty(), "expected at least 1 hit from BM25 search");
        assert_eq!(bm25_hits[0].id, "row1");
        assert_eq!(bm25_hits[0].text, row1.text);
        assert_eq!(bm25_hits[0].path, row1.path);
        assert_eq!(bm25_hits[0].source, row1.source);
        assert_eq!(bm25_hits[0].created_at, row1.created_at);
        assert!(bm25_hits[0].score > 0.0, "expected positive BM25 score, got {}", bm25_hits[0].score);

        // Dense KNN search returning full metadata
        let knn_hits = store
            .knn_v2(&name, &VEC_A, 1, FP_A)
            .await
            .expect("knn_v2 runs dense vector search");
        assert_eq!(knn_hits.len(), 1);
        assert_eq!(knn_hits[0].id, "row1");
        assert_eq!(knn_hits[0].text, row1.text);
        assert!(knn_hits[0].score < DISTANCE_EPSILON, "expected distance ~0.0, got {}", knn_hits[0].score);

        // List id hashes query
        let id_hashes = store
            .list_id_hashes_v2(&name, FP_A)
            .await
            .expect("list_id_hashes_v2 returns id and content hash map");
        assert_eq!(id_hashes.len(), 2);
        assert_eq!(id_hashes.get("row1").map(String::as_str), Some("hash_row1_blake3"));
        assert_eq!(id_hashes.get("row2").map(String::as_str), Some("hash_row2_blake3"));

        store
            .drop_collection(&name)
            .await
            .expect("drop the live test collection");
    }
}
